// Code generated by jassgen; DO NOT EDIT.
// Panic-bodied API skeleton — implemented in M5.

package litd

func (u Unit) Paused() bool {
	panic("litd: not implemented (M5)")
}

func (u Unit) SetPaused(paused bool) {
	panic("litd: not implemented (M5)")
}

