package main

// emit_lua.go generates the Lua binding descriptors from api-manifest.json —
// the SAME source as the Go stub surface, so the two surfaces cannot drift
// (G2.7, D-2026-06-11-8). One descriptor per canonical mapped symbol;
// tombstoned entries get none. The output is a compiling Go file (package
// luabind); the actual VM registration is wired in M5. The AI-domain surface
// (litd/ai) is kept in a separate descriptor slice to preserve R-EXEC-3
// isolation.
//
// Binding-name convention: the Lua global name is the canonical Go symbol with
// '.' replaced by '_' (e.g. "Unit.Paused" -> "Unit_Paused"). Free functions
// (helpers/ai) keep their bare name. This mirrors the Go surface exactly so a
// rename in the manifest renames both bindings in lockstep.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const luabindDir = "litd/luabind"

// luaBinding is one generated descriptor.
type luaBinding struct {
	LuaName     string
	Package     string
	Symbol      string
	GoSignature string
}

// luaBindingName derives the Lua global name from a canonical symbol.
func luaBindingName(symbol string) string {
	return strings.ReplaceAll(symbol, ".", "_")
}

// CollectLuaBindings splits mapped manifest symbols into the core surface
// (litd/api + litd/api/helpers) and the AI-domain surface (litd/ai), deduping
// by symbol (D3 collapse never produces two mapped entries for one symbol, but
// dedupe defensively). Returns (core, ai).
func CollectLuaBindings(m Manifest) (core, ai []luaBinding) {
	seen := map[string]bool{}
	for _, f := range m.Functions {
		if f.Disposition != "mapped" || f.GoMapping == nil {
			continue
		}
		if seen[f.GoMapping.Symbol] {
			continue
		}
		seen[f.GoMapping.Symbol] = true
		b := luaBinding{
			LuaName:     luaBindingName(f.GoMapping.Symbol),
			Package:     f.GoMapping.Package,
			Symbol:      f.GoMapping.Symbol,
			GoSignature: f.GoMapping.GoSignature,
		}
		if f.GoMapping.Package == "litd/ai" {
			ai = append(ai, b)
		} else {
			core = append(core, b)
		}
	}
	sort.Slice(core, func(i, j int) bool { return core[i].LuaName < core[j].LuaName })
	sort.Slice(ai, func(i, j int) bool { return ai[i].LuaName < ai[j].LuaName })
	return core, ai
}

// RenderLuaBindings renders the generated luabind source.
func RenderLuaBindings(m Manifest) string {
	core, ai := CollectLuaBindings(m)
	var b strings.Builder
	b.WriteString("// Code generated by jassgen; DO NOT EDIT.\n")
	b.WriteString("// Lua binding descriptors derived from api-manifest.json (G2.7).\n")
	b.WriteString("// VM registration is wired in M5; these descriptors are the contract.\n\n")
	b.WriteString("package luabind\n\n")
	b.WriteString("// Binding is one Lua global -> canonical Go symbol descriptor.\n")
	b.WriteString("type Binding struct {\n")
	b.WriteString("\tLuaName     string\n")
	b.WriteString("\tPackage     string\n")
	b.WriteString("\tSymbol      string\n")
	b.WriteString("\tGoSignature string\n")
	b.WriteString("}\n\n")
	writeBindingSlice(&b, "Bindings", "core API surface (litd/api + litd/api/helpers)", core)
	b.WriteString("\n")
	writeBindingSlice(&b, "AIBindings", "AI-domain surface (litd/ai, R-EXEC-3 isolated)", ai)
	return b.String()
}

func writeBindingSlice(b *strings.Builder, name, doc string, bs []luaBinding) {
	fmt.Fprintf(b, "// %s is the %s.\n", name, doc)
	fmt.Fprintf(b, "var %s = []Binding{\n", name)
	for _, bd := range bs {
		fmt.Fprintf(b, "\t{LuaName: %q, Package: %q, Symbol: %q, GoSignature: %q},\n",
			bd.LuaName, bd.Package, bd.Symbol, bd.GoSignature)
	}
	b.WriteString("}\n")
}

// WriteLuaBindings writes the generated file.
func WriteLuaBindings(m Manifest) error {
	if err := os.MkdirAll(luabindDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(luabindDir, "bindings_gen.go"), []byte(RenderLuaBindings(m)), 0o644)
}
