package main

import (
	"os"
	"path/filepath"
	"testing"
)

func manifestWith(syms ...GoMapping) Manifest {
	m := Manifest{SchemaVersion: 1}
	for i, gm := range syms {
		g := gm
		m.Functions = append(m.Functions, FunctionEntry{
			Name:           "Src" + string(rune('A'+i)),
			Origin:         "common.j",
			Signature:      Signature{Params: []ParamEntry{}, Returns: "nothing"},
			Classification: "D3",
			ClassifiedBy:   "override",
			Disposition:    "mapped",
			GoMapping:      &g,
		})
	}
	return m
}

// TestRemoveStubFileRetiresOrphan guards the second retirement hole: when the
// last stub in a package is hand-implemented (toEmit==0), the stale generated
// file must be pruned, not left behind to collide with the real method.
// removeStubFile deletes it and is idempotent (a missing file is not an error).
func TestRemoveStubFileRetiresOrphan(t *testing.T) {
	dir := t.TempDir()
	tgt := pkgTarget{dir: dir, pkgName: "litd"}
	path := filepath.Join(dir, "api_stubs_gen.go")
	if err := os.WriteFile(path, []byte("// Code generated by jassgen; DO NOT EDIT.\npackage litd\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeStubFile(tgt); err != nil {
		t.Fatalf("removeStubFile: %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("stub file not removed: stat err = %v", err)
	}
	// Idempotent: removing an already-absent file is not an error.
	if err := removeStubFile(tgt); err != nil {
		t.Errorf("removeStubFile on missing file = %v, want nil", err)
	}
}

func TestSplitSymbol(t *testing.T) {
	if r, n := splitSymbol("Unit.SetPosition"); r != "Unit" || n != "SetPosition" {
		t.Errorf("got %q.%q", r, n)
	}
	if r, n := splitSymbol("PolledWait"); r != "" || n != "PolledWait" {
		t.Errorf("got %q.%q, want free function", r, n)
	}
}

func TestExistingSymbolsSkipsHandWritten(t *testing.T) {
	// litd/api hand-implements Unit.SetLife; the generator must detect it.
	existing, err := existingSymbols("../../litd/api")
	if err != nil {
		t.Fatalf("scan litd/api: %v", err)
	}
	if !existing["Unit.SetLife"] {
		t.Error("expected Unit.SetLife to be detected as already implemented")
	}
	if existing["Unit.NeverDefinedXYZ"] {
		t.Error("phantom symbol reported as existing")
	}
}

// TestExistingSymbolsExcludesGeneratedStub is the regression guard for the
// stub-retirement bug (#360): existingSymbols must NOT count jassgen's own
// generated stub file, or a stub could never retire — once a symbol is
// hand-written it would collide with its own panic stub as a duplicate method.
//
// The fixture is a synthetic package dir (not the live tree, which no longer
// carries any unimplemented stub now that Unit.Paused/SetPaused are real): one
// generated stub file declaring Stub.Only, and one hand-written file declaring
// Hand.Written. existingSymbols must exclude Stub.Only and include Hand.Written.
func TestExistingSymbolsExcludesGeneratedStub(t *testing.T) {
	dir := t.TempDir()
	stub := "// Code generated by jassgen; DO NOT EDIT.\n" +
		"// Panic-bodied API skeleton — implemented in M5.\n\n" +
		"package litd\n\n" +
		"func (s Stub) Only() bool {\n\tpanic(\"litd: not implemented (M5)\")\n}\n"
	hand := "package litd\n\nfunc (h Hand) Written() bool { return true }\n"
	if err := os.WriteFile(filepath.Join(dir, "api_stubs_gen.go"), []byte(stub), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "hand.go"), []byte(hand), 0o644); err != nil {
		t.Fatal(err)
	}

	existing, err := existingSymbols(dir)
	if err != nil {
		t.Fatalf("scan fixture: %v", err)
	}
	if existing["Stub.Only"] {
		t.Error("Stub.Only (only in the generated stub) must not count as an existing implementation")
	}
	if !existing["Hand.Written"] {
		t.Error("hand-written Hand.Written must be detected as existing")
	}
}

// TestGenerateStubsD3CollapseAndSkip drives GenerateStubs over a temp dir-free
// manifest path that targets only new packages, asserting D3 collapse (one
// symbol claimed twice => one stub) does not double-emit.
func TestGenerateStubsDedup(t *testing.T) {
	// two manifest entries map to the SAME canonical symbol (D3 collapse)
	m := Manifest{SchemaVersion: 1, Functions: []FunctionEntry{
		{Name: "SetUnitX", Origin: "common.j", Signature: Signature{Params: []ParamEntry{}, Returns: "nothing"},
			Classification: "D3", ClassifiedBy: "override", Disposition: "mapped",
			GoMapping: &GoMapping{Symbol: "Unit.SetPosition", Package: "litd/api", GoSignature: "(pos Vec2)"}},
		{Name: "SetUnitPosition", Origin: "common.j", Signature: Signature{Params: []ParamEntry{}, Returns: "nothing"},
			Classification: "D3", ClassifiedBy: "override", Disposition: "mapped",
			GoMapping: &GoMapping{Symbol: "Unit.SetPosition", Package: "litd/api", GoSignature: "(pos Vec2)"}},
	}}
	// Collect via the dedupe logic without writing files: reuse the front of
	// GenerateStubs by counting distinct (recv.name).
	seen := map[string]bool{}
	count := 0
	for _, f := range m.Functions {
		r, n := splitSymbol(f.GoMapping.Symbol)
		k := r + "." + n
		if !seen[k] {
			seen[k] = true
			count++
		}
	}
	if count != 1 {
		t.Errorf("D3 collapse: distinct symbols = %d, want 1", count)
	}
}
