package main

// emit_stubs.go generates compiling, panic-bodied Go API stubs — one per
// canonical symbol in the manifest's goMapping (tooling.md §2.2 step 5). It is
// the skeleton M5 fills in. Symbols already implemented by hand in the tree are
// skipped (detected via go/parser) so generation never clobbers real code. D3
// collapses produce exactly one stub (one goMapping symbol => one stub).
// Output is deterministic and carries a DO-NOT-EDIT header.

import (
	"fmt"
	"go/ast"
	goparser "go/parser"
	gotoken "go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// pkgTarget maps a manifest goMapping.package to an output directory + Go
// package name.
type pkgTarget struct {
	dir     string
	pkgName string
}

var pkgTargets = map[string]pkgTarget{
	"litd/api":         {"litd/api", "litd"},
	"litd/api/helpers": {"litd/api/helpers", "helpers"},
	"litd/ai":          {"litd/ai", "ai"},
}

// stubSym is a canonical symbol to stub.
type stubSym struct {
	recv string // receiver type, "" for a free function
	name string // method/function name
	sig  string // Go signature text e.g. "() bool" or "(pos Vec2)"
}

// GenerateStubs writes one generated file per package directory. It returns,
// per package, the symbols emitted and the symbols skipped (already defined).
func GenerateStubs(m Manifest) (emitted map[string][]string, skipped map[string][]string, err error) {
	emitted = map[string][]string{}
	skipped = map[string][]string{}

	byPkg := map[string][]stubSym{}
	for _, f := range m.Functions {
		if f.Disposition != "mapped" || f.GoMapping == nil {
			continue
		}
		pkg := f.GoMapping.Package
		recv, name := splitSymbol(f.GoMapping.Symbol)
		byPkg[pkg] = append(byPkg[pkg], stubSym{recv: recv, name: name, sig: f.GoMapping.GoSignature})
	}

	for pkg, syms := range byPkg {
		tgt, ok := pkgTargets[pkg]
		if !ok {
			return nil, nil, fmt.Errorf("unknown package %q in goMapping", pkg)
		}
		existing, perr := existingSymbols(tgt.dir)
		if perr != nil {
			return nil, nil, perr
		}

		// dedupe symbols (D3 collapse: many manifest entries -> one symbol)
		seen := map[string]bool{}
		var toEmit []stubSym
		for _, s := range syms {
			key := s.recv + "." + s.name
			if seen[key] {
				continue
			}
			seen[key] = true
			if existing[key] {
				skipped[pkg] = append(skipped[pkg], key)
				continue
			}
			toEmit = append(toEmit, s)
			emitted[pkg] = append(emitted[pkg], key)
		}
		sort.Strings(emitted[pkg])
		sort.Strings(skipped[pkg])
		sort.Slice(toEmit, func(i, j int) bool {
			return toEmit[i].recv+"."+toEmit[i].name < toEmit[j].recv+"."+toEmit[j].name
		})

		if len(toEmit) == 0 {
			continue
		}
		if err := writeStubFile(tgt, toEmit); err != nil {
			return nil, nil, err
		}
	}
	return emitted, skipped, nil
}

// splitSymbol parses "Type.Method" into (Type, Method); a bare "Func" yields
// ("", "Func").
func splitSymbol(sym string) (recv, name string) {
	if i := strings.LastIndexByte(sym, '.'); i >= 0 {
		return sym[:i], sym[i+1:]
	}
	return "", sym
}

// existingSymbols parses every .go file in dir (non-recursive, non-test) and
// returns the set of "Recv.Name" and ".Func" already declared. A missing dir
// yields an empty set (new package).
func existingSymbols(dir string) (map[string]bool, error) {
	out := map[string]bool{}
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return out, nil
		}
		return nil, err
	}
	fset := gotoken.NewFileSet()
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := goparser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, goparser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", e.Name(), err)
		}
		// Skip jassgen's own generated stub file. A panic stub is NOT a real
		// implementation; counting it as "existing" would make every stub
		// permanent — once a symbol is hand-written it would collide with its
		// own stub as a duplicate method, and the generator could never retire
		// the stub. Only hand-written code counts as existing.
		if isGeneratedStub(f) {
			continue
		}
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}
			recv := ""
			if fn.Recv != nil && len(fn.Recv.List) > 0 {
				recv = receiverTypeName(fn.Recv.List[0].Type)
			}
			out[recv+"."+fn.Name.Name] = true
		}
	}
	return out, nil
}

// isGeneratedStub reports whether f carries jassgen's generated-file header
// (the standard "Code generated … DO NOT EDIT." marker). Such files are
// jassgen's own output and must not count as hand-written implementations.
func isGeneratedStub(f *ast.File) bool {
	for _, cg := range f.Comments {
		for _, c := range cg.List {
			if strings.Contains(c.Text, "Code generated by jassgen") {
				return true
			}
		}
		// header comments only appear at the top; stop after the first group
		// that precedes the package clause
		if cg.End() > f.Package {
			break
		}
	}
	return false
}

func receiverTypeName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return receiverTypeName(t.X)
	}
	return ""
}

func writeStubFile(tgt pkgTarget, syms []stubSym) error {
	var b strings.Builder
	b.WriteString("// Code generated by jassgen; DO NOT EDIT.\n")
	b.WriteString("// Panic-bodied API skeleton — implemented in M5.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", tgt.pkgName)

	const body = `	panic("litd: not implemented (M5)")`
	for _, s := range syms {
		sig := s.sig
		if sig == "" {
			sig = "()"
		}
		if s.recv == "" {
			fmt.Fprintf(&b, "func %s%s {\n%s\n}\n\n", s.name, sig, body)
		} else {
			recvVar := strings.ToLower(s.recv[:1])
			fmt.Fprintf(&b, "func (%s %s) %s%s {\n%s\n}\n\n", recvVar, s.recv, s.name, sig, body)
		}
	}
	if err := os.MkdirAll(tgt.dir, 0o755); err != nil {
		return err
	}
	out := filepath.Join(tgt.dir, "api_stubs_gen.go")
	return os.WriteFile(out, []byte(b.String()), 0o644)
}
