package main

// emit_table.go generates the JASS->Go migration table (tooling.md §2.2 step 5
// / G2.6, naming-and-style §3): one markdown row per source function so a WC3
// modder searching any name gets an answer — a canonical Go symbol, a tombstone
// with its reason, or an explicit "pending" for the unresolved M2 backlog.
// Never a gap. Deterministic (origin, then source order); DO-NOT-EDIT header.

import (
	"fmt"
	"sort"
	"strings"
)

// originRank orders the table by file, preserving source order within each.
var originRank = map[string]int{"common": 0, "blizzard": 1, "commonai": 2}

// RenderMappingTable renders the full migration table from the classification
// universe. It returns the markdown and the row count.
func RenderMappingTable(cs []Classification) (string, int) {
	// Build member -> canonical symbol from D3 collapse declarations so every
	// family member row points at the same canonical Go symbol.
	collapse := map[string]Classification{}
	for _, c := range cs {
		for _, member := range c.CollapsesWith {
			collapse[member] = c
		}
	}

	rows := append([]Classification{}, cs...)
	sort.SliceStable(rows, func(i, j int) bool {
		return originRank[rows[i].Origin] < originRank[rows[j].Origin]
	})

	var b strings.Builder
	b.WriteString("<!-- Code generated by jassgen; DO NOT EDIT. Regenerate: go run ./tools/jassgen -emit-table -->\n\n")
	b.WriteString("# JASS → Go mapping table\n\n")
	b.WriteString("One row per source function across common.j, blizzard.j, and common.ai. ")
	b.WriteString("`canonical / disposition` is the Go symbol an entry maps to, a tombstone with reason, ")
	b.WriteString("or `pending` for symbols not yet resolved (the M2 mapping backlog).\n\n")
	b.WriteString("| JASS name | origin | rule | canonical / disposition |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, c := range rows {
		rule := string(c.Class)
		cell := dispositionCell(c)
		// If this row is a D3 collapse member, point it at the canonical symbol.
		if canon, ok := collapse[c.Name]; ok && c.GoMapping == "" {
			rule = string(canon.Class)
			pkg := canon.Package
			if pkg == "" {
				pkg = "litd/api"
			}
			cell = fmt.Sprintf("`%s.%s` (D3 collapse → %s)", pkg, canon.GoMapping, canon.Name)
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", c.Name, originFile[c.Origin], rule, cell)
	}
	return b.String(), len(rows)
}

// dispositionCell renders the canonical/disposition column for one entry.
func dispositionCell(c Classification) string {
	if c.Tombstone != "" {
		detail := strings.TrimPrefix(c.Evidence, "tombstone: ")
		return fmt.Sprintf("**tombstoned** (%s): %s", c.Tombstone, detail)
	}
	if c.GoMapping != "" {
		pkg := c.Package
		if pkg == "" {
			pkg = "litd/api"
		}
		return fmt.Sprintf("`%s.%s`", pkg, c.GoMapping)
	}
	return "_pending (M2 backlog)_"
}
