// Code generated by jassgen; DO NOT EDIT.
// Lua binding descriptors derived from api-manifest.json (G2.7).
// VM registration is wired in M5; these descriptors are the contract.

package luabind

// Binding is one Lua global -> canonical Go symbol descriptor.
type Binding struct {
	LuaName     string
	Package     string
	Symbol      string
	GoSignature string
}

// Bindings is the core API surface (litd/api + litd/api/helpers).
var Bindings = []Binding{
	{LuaName: "Game_CreateUnit", Package: "litd/api", Symbol: "Game.CreateUnit", GoSignature: "(owner Player, typ UnitType, pos Vec2, facing Angle) Unit"},
	{LuaName: "PolledWait", Package: "litd/api/helpers", Symbol: "PolledWait", GoSignature: "(seconds float64)"},
	{LuaName: "Unit_AcquireRange", Package: "litd/api", Symbol: "Unit.AcquireRange", GoSignature: "() float64"},
	{LuaName: "Unit_AddExperience", Package: "litd/api", Symbol: "Unit.AddExperience", GoSignature: "(xp int)"},
	{LuaName: "Unit_Agility", Package: "litd/api", Symbol: "Unit.Agility", GoSignature: "() int"},
	{LuaName: "Unit_Alive", Package: "litd/api", Symbol: "Unit.Alive", GoSignature: "() bool"},
	{LuaName: "Unit_Armor", Package: "litd/api", Symbol: "Unit.Armor", GoSignature: "() float64"},
	{LuaName: "Unit_CurrentOrder", Package: "litd/api", Symbol: "Unit.CurrentOrder", GoSignature: "() Order"},
	{LuaName: "Unit_DefaultAcquireRange", Package: "litd/api", Symbol: "Unit.DefaultAcquireRange", GoSignature: "() float64"},
	{LuaName: "Unit_DefaultMoveSpeed", Package: "litd/api", Symbol: "Unit.DefaultMoveSpeed", GoSignature: "() float64"},
	{LuaName: "Unit_DefaultTurnSpeed", Package: "litd/api", Symbol: "Unit.DefaultTurnSpeed", GoSignature: "() float64"},
	{LuaName: "Unit_Facing", Package: "litd/api", Symbol: "Unit.Facing", GoSignature: "() Angle"},
	{LuaName: "Unit_FoodMade", Package: "litd/api", Symbol: "Unit.FoodMade", GoSignature: "() int"},
	{LuaName: "Unit_FoodUsed", Package: "litd/api", Symbol: "Unit.FoodUsed", GoSignature: "() int"},
	{LuaName: "Unit_HeroLevel", Package: "litd/api", Symbol: "Unit.HeroLevel", GoSignature: "() int"},
	{LuaName: "Unit_HeroXP", Package: "litd/api", Symbol: "Unit.HeroXP", GoSignature: "() int"},
	{LuaName: "Unit_Intelligence", Package: "litd/api", Symbol: "Unit.Intelligence", GoSignature: "() int"},
	{LuaName: "Unit_InventorySize", Package: "litd/api", Symbol: "Unit.InventorySize", GoSignature: "() int"},
	{LuaName: "Unit_Invulnerable", Package: "litd/api", Symbol: "Unit.Invulnerable", GoSignature: "() bool"},
	{LuaName: "Unit_IsHidden", Package: "litd/api", Symbol: "Unit.IsHidden", GoSignature: "() bool"},
	{LuaName: "Unit_Kill", Package: "litd/api", Symbol: "Unit.Kill", GoSignature: "()"},
	{LuaName: "Unit_Life", Package: "litd/api", Symbol: "Unit.Life", GoSignature: "() float64"},
	{LuaName: "Unit_MaxLife", Package: "litd/api", Symbol: "Unit.MaxLife", GoSignature: "() float64"},
	{LuaName: "Unit_MaxMana", Package: "litd/api", Symbol: "Unit.MaxMana", GoSignature: "() float64"},
	{LuaName: "Unit_ModifySkillPoints", Package: "litd/api", Symbol: "Unit.ModifySkillPoints", GoSignature: "(delta int) bool"},
	{LuaName: "Unit_MoveSpeed", Package: "litd/api", Symbol: "Unit.MoveSpeed", GoSignature: "() float64"},
	{LuaName: "Unit_Order", Package: "litd/api", Symbol: "Unit.Order", GoSignature: "(ord Order, target OrderTarget) bool"},
	{LuaName: "Unit_Owner", Package: "litd/api", Symbol: "Unit.Owner", GoSignature: "() Player"},
	{LuaName: "Unit_Paused", Package: "litd/api", Symbol: "Unit.Paused", GoSignature: "() bool"},
	{LuaName: "Unit_PointValue", Package: "litd/api", Symbol: "Unit.PointValue", GoSignature: "() int"},
	{LuaName: "Unit_Position", Package: "litd/api", Symbol: "Unit.Position", GoSignature: "() Vec2"},
	{LuaName: "Unit_Remove", Package: "litd/api", Symbol: "Unit.Remove", GoSignature: "()"},
	{LuaName: "Unit_SetAcquireRange", Package: "litd/api", Symbol: "Unit.SetAcquireRange", GoSignature: "(v float64)"},
	{LuaName: "Unit_SetAgility", Package: "litd/api", Symbol: "Unit.SetAgility", GoSignature: "(v int)"},
	{LuaName: "Unit_SetFacing", Package: "litd/api", Symbol: "Unit.SetFacing", GoSignature: "(a Angle)"},
	{LuaName: "Unit_SetIntelligence", Package: "litd/api", Symbol: "Unit.SetIntelligence", GoSignature: "(v int)"},
	{LuaName: "Unit_SetInvulnerable", Package: "litd/api", Symbol: "Unit.SetInvulnerable", GoSignature: "(on bool)"},
	{LuaName: "Unit_SetLife", Package: "litd/api", Symbol: "Unit.SetLife", GoSignature: "(v float64)"},
	{LuaName: "Unit_SetMoveSpeed", Package: "litd/api", Symbol: "Unit.SetMoveSpeed", GoSignature: "(v float64)"},
	{LuaName: "Unit_SetOwner", Package: "litd/api", Symbol: "Unit.SetOwner", GoSignature: "(p Player, changeColor bool)"},
	{LuaName: "Unit_SetPaused", Package: "litd/api", Symbol: "Unit.SetPaused", GoSignature: "(paused bool)"},
	{LuaName: "Unit_SetPosition", Package: "litd/api", Symbol: "Unit.SetPosition", GoSignature: "(pos Vec2)"},
	{LuaName: "Unit_SetStrength", Package: "litd/api", Symbol: "Unit.SetStrength", GoSignature: "(v int)"},
	{LuaName: "Unit_SetTurnSpeed", Package: "litd/api", Symbol: "Unit.SetTurnSpeed", GoSignature: "(radPerSec float64)"},
	{LuaName: "Unit_SetUserData", Package: "litd/api", Symbol: "Unit.SetUserData", GoSignature: "(v int)"},
	{LuaName: "Unit_Show", Package: "litd/api", Symbol: "Unit.Show", GoSignature: "(show bool)"},
	{LuaName: "Unit_SkillPoints", Package: "litd/api", Symbol: "Unit.SkillPoints", GoSignature: "() int"},
	{LuaName: "Unit_Strength", Package: "litd/api", Symbol: "Unit.Strength", GoSignature: "() int"},
	{LuaName: "Unit_TurnSpeed", Package: "litd/api", Symbol: "Unit.TurnSpeed", GoSignature: "() float64"},
	{LuaName: "Unit_Type", Package: "litd/api", Symbol: "Unit.Type", GoSignature: "() UnitType"},
	{LuaName: "Unit_UserData", Package: "litd/api", Symbol: "Unit.UserData", GoSignature: "() int"},
}

// AIBindings is the AI-domain surface (litd/ai, R-EXEC-3 isolated).
var AIBindings = []Binding{
	{LuaName: "UnitCount", Package: "litd/ai", Symbol: "UnitCount", GoSignature: "(unitTypeID int) int"},
}
