// Code generated by jassgen; DO NOT EDIT.
// Lua binding dispatch derived from api-manifest.json (#267): 5 of 408 mapped
// verbs bound. The rest need handle/enum/slice/Game/variadic marshaling not yet
// emitted by the generator and are intentionally unbound (no silent drop).

package luabind

import (
	lua "github.com/yuin/gopher-lua"
)

// registerValueMath installs the generated value-math globals on L.
func registerValueMath(L *lua.LState) {
	L.SetGlobal("Angle_Degrees", L.NewFunction(bindAngleDegrees))
	L.SetGlobal("Vec2_Add", L.NewFunction(bindVec2Add))
	L.SetGlobal("Vec2_AngleTo", L.NewFunction(bindVec2AngleTo))
	L.SetGlobal("Vec2_DistanceTo", L.NewFunction(bindVec2DistanceTo))
	L.SetGlobal("Vec2_Polar", L.NewFunction(bindVec2Polar))
}

// Angle_Degrees -> Angle.Degrees() float64
func bindAngleDegrees(L *lua.LState) int {
	recv := argAngle(L, 1)
	res := recv.Degrees()
	L.Push(lua.LNumber(res))
	return 1
}

// Vec2_Add -> Vec2.Add(o Vec2) Vec2
func bindVec2Add(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argVec2(L, 2)
	res := recv.Add(a0)
	L.Push(vec2ToLua(L, res))
	return 1
}

// Vec2_AngleTo -> Vec2.AngleTo(o Vec2) Angle
func bindVec2AngleTo(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argVec2(L, 2)
	res := recv.AngleTo(a0)
	L.Push(angleToLua(res))
	return 1
}

// Vec2_DistanceTo -> Vec2.DistanceTo(o Vec2) float64
func bindVec2DistanceTo(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argVec2(L, 2)
	res := recv.DistanceTo(a0)
	L.Push(lua.LNumber(res))
	return 1
}

// Vec2_Polar -> Vec2.Polar(a Angle, dist float64) Vec2
func bindVec2Polar(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argAngle(L, 2)
	a1 := float64(L.CheckNumber(3))
	res := recv.Polar(a0, a1)
	L.Push(vec2ToLua(L, res))
	return 1
}
