// Code generated by jassgen; DO NOT EDIT.
// Lua binding dispatch derived from api-manifest.json (#267): 104 of 408 mapped
// verbs bound. The rest need handle/enum/slice/Game/variadic marshaling not yet
// emitted by the generator and are intentionally unbound (no silent drop).

package luabind

import (
	lua "github.com/yuin/gopher-lua"
)

// registerGenerated installs the generated value/handle-verb globals on L.
// These verbs need no game: value types are pure and a handle userdata
// self-carries its *Game. Game-bound and Player/enum verbs install elsewhere.
func registerGenerated(L *lua.LState) {
	L.SetGlobal("Angle_Degrees", L.NewFunction(bindAngleDegrees))
	L.SetGlobal("Destructable_Dead", L.NewFunction(bindDestructableDead))
	L.SetGlobal("Destructable_Invulnerable", L.NewFunction(bindDestructableInvulnerable))
	L.SetGlobal("Destructable_Kill", L.NewFunction(bindDestructableKill))
	L.SetGlobal("Destructable_Life", L.NewFunction(bindDestructableLife))
	L.SetGlobal("Destructable_MaxLife", L.NewFunction(bindDestructableMaxLife))
	L.SetGlobal("Destructable_PlayAnimation", L.NewFunction(bindDestructablePlayAnimation))
	L.SetGlobal("Destructable_Resurrect", L.NewFunction(bindDestructableResurrect))
	L.SetGlobal("Destructable_SetInvulnerable", L.NewFunction(bindDestructableSetInvulnerable))
	L.SetGlobal("Destructable_SetLife", L.NewFunction(bindDestructableSetLife))
	L.SetGlobal("Effect_Destroy", L.NewFunction(bindEffectDestroy))
	L.SetGlobal("Effect_SetColor", L.NewFunction(bindEffectSetColor))
	L.SetGlobal("Effect_SetPosition", L.NewFunction(bindEffectSetPosition))
	L.SetGlobal("Effect_SetScale", L.NewFunction(bindEffectSetScale))
	L.SetGlobal("Item_Charges", L.NewFunction(bindItemCharges))
	L.SetGlobal("Item_Position", L.NewFunction(bindItemPosition))
	L.SetGlobal("Item_Remove", L.NewFunction(bindItemRemove))
	L.SetGlobal("Item_SetCharges", L.NewFunction(bindItemSetCharges))
	L.SetGlobal("Rect_Center", L.NewFunction(bindRectCenter))
	L.SetGlobal("Rect_Contains", L.NewFunction(bindRectContains))
	L.SetGlobal("Rect_Height", L.NewFunction(bindRectHeight))
	L.SetGlobal("Rect_Max", L.NewFunction(bindRectMax))
	L.SetGlobal("Rect_Min", L.NewFunction(bindRectMin))
	L.SetGlobal("Rect_Offset", L.NewFunction(bindRectOffset))
	L.SetGlobal("Rect_Width", L.NewFunction(bindRectWidth))
	L.SetGlobal("Unit_AcquireRange", L.NewFunction(bindUnitAcquireRange))
	L.SetGlobal("Unit_AddExperience", L.NewFunction(bindUnitAddExperience))
	L.SetGlobal("Unit_AddItem", L.NewFunction(bindUnitAddItem))
	L.SetGlobal("Unit_Agility", L.NewFunction(bindUnitAgility))
	L.SetGlobal("Unit_Alive", L.NewFunction(bindUnitAlive))
	L.SetGlobal("Unit_Armor", L.NewFunction(bindUnitArmor))
	L.SetGlobal("Unit_BuffCount", L.NewFunction(bindUnitBuffCount))
	L.SetGlobal("Unit_CollisionSize", L.NewFunction(bindUnitCollisionSize))
	L.SetGlobal("Unit_DefaultAcquireRange", L.NewFunction(bindUnitDefaultAcquireRange))
	L.SetGlobal("Unit_DefaultFlyHeight", L.NewFunction(bindUnitDefaultFlyHeight))
	L.SetGlobal("Unit_DefaultMoveSpeed", L.NewFunction(bindUnitDefaultMoveSpeed))
	L.SetGlobal("Unit_DefaultPropWindow", L.NewFunction(bindUnitDefaultPropWindow))
	L.SetGlobal("Unit_DefaultTurnSpeed", L.NewFunction(bindUnitDefaultTurnSpeed))
	L.SetGlobal("Unit_DropItem", L.NewFunction(bindUnitDropItem))
	L.SetGlobal("Unit_ExperienceSuspended", L.NewFunction(bindUnitExperienceSuspended))
	L.SetGlobal("Unit_Facing", L.NewFunction(bindUnitFacing))
	L.SetGlobal("Unit_FlyHeight", L.NewFunction(bindUnitFlyHeight))
	L.SetGlobal("Unit_FoodMade", L.NewFunction(bindUnitFoodMade))
	L.SetGlobal("Unit_FoodUsed", L.NewFunction(bindUnitFoodUsed))
	L.SetGlobal("Unit_GiveItemTo", L.NewFunction(bindUnitGiveItemTo))
	L.SetGlobal("Unit_HeroLevel", L.NewFunction(bindUnitHeroLevel))
	L.SetGlobal("Unit_HeroXP", L.NewFunction(bindUnitHeroXP))
	L.SetGlobal("Unit_ID", L.NewFunction(bindUnitID))
	L.SetGlobal("Unit_InRange", L.NewFunction(bindUnitInRange))
	L.SetGlobal("Unit_InRangeOf", L.NewFunction(bindUnitInRangeOf))
	L.SetGlobal("Unit_Intelligence", L.NewFunction(bindUnitIntelligence))
	L.SetGlobal("Unit_InventorySize", L.NewFunction(bindUnitInventorySize))
	L.SetGlobal("Unit_Invulnerable", L.NewFunction(bindUnitInvulnerable))
	L.SetGlobal("Unit_IsHidden", L.NewFunction(bindUnitIsHidden))
	L.SetGlobal("Unit_ItemCount", L.NewFunction(bindUnitItemCount))
	L.SetGlobal("Unit_ItemInSlot", L.NewFunction(bindUnitItemInSlot))
	L.SetGlobal("Unit_Kill", L.NewFunction(bindUnitKill))
	L.SetGlobal("Unit_LearnSkill", L.NewFunction(bindUnitLearnSkill))
	L.SetGlobal("Unit_Level", L.NewFunction(bindUnitLevel))
	L.SetGlobal("Unit_Life", L.NewFunction(bindUnitLife))
	L.SetGlobal("Unit_LifePercent", L.NewFunction(bindUnitLifePercent))
	L.SetGlobal("Unit_ManaPercent", L.NewFunction(bindUnitManaPercent))
	L.SetGlobal("Unit_MaxLife", L.NewFunction(bindUnitMaxLife))
	L.SetGlobal("Unit_MaxMana", L.NewFunction(bindUnitMaxMana))
	L.SetGlobal("Unit_ModifySkillPoints", L.NewFunction(bindUnitModifySkillPoints))
	L.SetGlobal("Unit_MoveSpeed", L.NewFunction(bindUnitMoveSpeed))
	L.SetGlobal("Unit_Name", L.NewFunction(bindUnitName))
	L.SetGlobal("Unit_Paused", L.NewFunction(bindUnitPaused))
	L.SetGlobal("Unit_PointValue", L.NewFunction(bindUnitPointValue))
	L.SetGlobal("Unit_Position", L.NewFunction(bindUnitPosition))
	L.SetGlobal("Unit_PropWindow", L.NewFunction(bindUnitPropWindow))
	L.SetGlobal("Unit_RallyPoint", L.NewFunction(bindUnitRallyPoint))
	L.SetGlobal("Unit_RallyUnit", L.NewFunction(bindUnitRallyUnit))
	L.SetGlobal("Unit_Remove", L.NewFunction(bindUnitRemove))
	L.SetGlobal("Unit_RemoveAllBuffs", L.NewFunction(bindUnitRemoveAllBuffs))
	L.SetGlobal("Unit_SetAcquireRange", L.NewFunction(bindUnitSetAcquireRange))
	L.SetGlobal("Unit_SetAgility", L.NewFunction(bindUnitSetAgility))
	L.SetGlobal("Unit_SetFacing", L.NewFunction(bindUnitSetFacing))
	L.SetGlobal("Unit_SetFlyHeight", L.NewFunction(bindUnitSetFlyHeight))
	L.SetGlobal("Unit_SetHeroLevel", L.NewFunction(bindUnitSetHeroLevel))
	L.SetGlobal("Unit_SetHeroXP", L.NewFunction(bindUnitSetHeroXP))
	L.SetGlobal("Unit_SetIntelligence", L.NewFunction(bindUnitSetIntelligence))
	L.SetGlobal("Unit_SetInvulnerable", L.NewFunction(bindUnitSetInvulnerable))
	L.SetGlobal("Unit_SetLife", L.NewFunction(bindUnitSetLife))
	L.SetGlobal("Unit_SetMaxLife", L.NewFunction(bindUnitSetMaxLife))
	L.SetGlobal("Unit_SetMaxMana", L.NewFunction(bindUnitSetMaxMana))
	L.SetGlobal("Unit_SetMoveSpeed", L.NewFunction(bindUnitSetMoveSpeed))
	L.SetGlobal("Unit_SetName", L.NewFunction(bindUnitSetName))
	L.SetGlobal("Unit_SetPaused", L.NewFunction(bindUnitSetPaused))
	L.SetGlobal("Unit_SetPosition", L.NewFunction(bindUnitSetPosition))
	L.SetGlobal("Unit_SetPropWindow", L.NewFunction(bindUnitSetPropWindow))
	L.SetGlobal("Unit_SetStrength", L.NewFunction(bindUnitSetStrength))
	L.SetGlobal("Unit_SetTurnSpeed", L.NewFunction(bindUnitSetTurnSpeed))
	L.SetGlobal("Unit_SetUserData", L.NewFunction(bindUnitSetUserData))
	L.SetGlobal("Unit_Show", L.NewFunction(bindUnitShow))
	L.SetGlobal("Unit_SkillPoints", L.NewFunction(bindUnitSkillPoints))
	L.SetGlobal("Unit_Strength", L.NewFunction(bindUnitStrength))
	L.SetGlobal("Unit_SuspendExperience", L.NewFunction(bindUnitSuspendExperience))
	L.SetGlobal("Unit_TurnSpeed", L.NewFunction(bindUnitTurnSpeed))
	L.SetGlobal("Unit_UserData", L.NewFunction(bindUnitUserData))
	L.SetGlobal("Vec2_Add", L.NewFunction(bindVec2Add))
	L.SetGlobal("Vec2_AngleTo", L.NewFunction(bindVec2AngleTo))
	L.SetGlobal("Vec2_DistanceTo", L.NewFunction(bindVec2DistanceTo))
	L.SetGlobal("Vec2_Polar", L.NewFunction(bindVec2Polar))
}

// Angle_Degrees -> Angle.Degrees() float64
func bindAngleDegrees(L *lua.LState) int {
	recv := argAngle(L, 1)
	res := recv.Degrees()
	L.Push(lua.LNumber(res))
	return 1
}

// Destructable_Dead -> Destructable.Dead() bool
func bindDestructableDead(L *lua.LState) int {
	recv := argDestructable(L, 1)
	res := recv.Dead()
	L.Push(lua.LBool(res))
	return 1
}

// Destructable_Invulnerable -> Destructable.Invulnerable() bool
func bindDestructableInvulnerable(L *lua.LState) int {
	recv := argDestructable(L, 1)
	res := recv.Invulnerable()
	L.Push(lua.LBool(res))
	return 1
}

// Destructable_Kill -> Destructable.Kill()
func bindDestructableKill(L *lua.LState) int {
	recv := argDestructable(L, 1)
	recv.Kill()
	return 0
}

// Destructable_Life -> Destructable.Life() int
func bindDestructableLife(L *lua.LState) int {
	recv := argDestructable(L, 1)
	res := recv.Life()
	L.Push(lua.LNumber(res))
	return 1
}

// Destructable_MaxLife -> Destructable.MaxLife() int
func bindDestructableMaxLife(L *lua.LState) int {
	recv := argDestructable(L, 1)
	res := recv.MaxLife()
	L.Push(lua.LNumber(res))
	return 1
}

// Destructable_PlayAnimation -> Destructable.PlayAnimation(name string)
func bindDestructablePlayAnimation(L *lua.LState) int {
	recv := argDestructable(L, 1)
	a0 := L.CheckString(2)
	recv.PlayAnimation(a0)
	return 0
}

// Destructable_Resurrect -> Destructable.Resurrect()
func bindDestructableResurrect(L *lua.LState) int {
	recv := argDestructable(L, 1)
	recv.Resurrect()
	return 0
}

// Destructable_SetInvulnerable -> Destructable.SetInvulnerable(b bool)
func bindDestructableSetInvulnerable(L *lua.LState) int {
	recv := argDestructable(L, 1)
	a0 := L.CheckBool(2)
	recv.SetInvulnerable(a0)
	return 0
}

// Destructable_SetLife -> Destructable.SetLife(v int)
func bindDestructableSetLife(L *lua.LState) int {
	recv := argDestructable(L, 1)
	a0 := L.CheckInt(2)
	recv.SetLife(a0)
	return 0
}

// Effect_Destroy -> Effect.Destroy()
func bindEffectDestroy(L *lua.LState) int {
	recv := argEffect(L, 1)
	recv.Destroy()
	return 0
}

// Effect_SetColor -> Effect.SetColor(r, g, b uint8)
func bindEffectSetColor(L *lua.LState) int {
	recv := argEffect(L, 1)
	a0 := uint8(L.CheckInt(2))
	a1 := uint8(L.CheckInt(3))
	a2 := uint8(L.CheckInt(4))
	recv.SetColor(a0, a1, a2)
	return 0
}

// Effect_SetPosition -> Effect.SetPosition(pos Vec2)
func bindEffectSetPosition(L *lua.LState) int {
	recv := argEffect(L, 1)
	a0 := argVec2(L, 2)
	recv.SetPosition(a0)
	return 0
}

// Effect_SetScale -> Effect.SetScale(scale float64)
func bindEffectSetScale(L *lua.LState) int {
	recv := argEffect(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetScale(a0)
	return 0
}

// Item_Charges -> Item.Charges() int
func bindItemCharges(L *lua.LState) int {
	recv := argItem(L, 1)
	res := recv.Charges()
	L.Push(lua.LNumber(res))
	return 1
}

// Item_Position -> Item.Position() Vec2
func bindItemPosition(L *lua.LState) int {
	recv := argItem(L, 1)
	res := recv.Position()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Item_Remove -> Item.Remove()
func bindItemRemove(L *lua.LState) int {
	recv := argItem(L, 1)
	recv.Remove()
	return 0
}

// Item_SetCharges -> Item.SetCharges(n int)
func bindItemSetCharges(L *lua.LState) int {
	recv := argItem(L, 1)
	a0 := L.CheckInt(2)
	recv.SetCharges(a0)
	return 0
}

// Rect_Center -> Rect.Center() Vec2
func bindRectCenter(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Center()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Rect_Contains -> Rect.Contains(p Vec2) bool
func bindRectContains(L *lua.LState) int {
	recv := argRect(L, 1)
	a0 := argVec2(L, 2)
	res := recv.Contains(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Rect_Height -> Rect.Height() float64
func bindRectHeight(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Height()
	L.Push(lua.LNumber(res))
	return 1
}

// Rect_Max -> Rect.Max() Vec2
func bindRectMax(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Max()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Rect_Min -> Rect.Min() Vec2
func bindRectMin(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Min()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Rect_Offset -> Rect.Offset(d Vec2) Rect
func bindRectOffset(L *lua.LState) int {
	recv := argRect(L, 1)
	a0 := argVec2(L, 2)
	res := recv.Offset(a0)
	L.Push(rectToLua(L, res))
	return 1
}

// Rect_Width -> Rect.Width() float64
func bindRectWidth(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Width()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_AcquireRange -> Unit.AcquireRange() float64
func bindUnitAcquireRange(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.AcquireRange()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_AddExperience -> Unit.AddExperience(xp int)
func bindUnitAddExperience(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.AddExperience(a0)
	return 0
}

// Unit_AddItem -> Unit.AddItem(it Item) bool
func bindUnitAddItem(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argItem(L, 2)
	res := recv.AddItem(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Agility -> Unit.Agility() int
func bindUnitAgility(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Agility()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Alive -> Unit.Alive() bool
func bindUnitAlive(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Alive()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Armor -> Unit.Armor() float64
func bindUnitArmor(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Armor()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_BuffCount -> Unit.BuffCount() int
func bindUnitBuffCount(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.BuffCount()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_CollisionSize -> Unit.CollisionSize() float64
func bindUnitCollisionSize(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.CollisionSize()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DefaultAcquireRange -> Unit.DefaultAcquireRange() float64
func bindUnitDefaultAcquireRange(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultAcquireRange()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DefaultFlyHeight -> Unit.DefaultFlyHeight() float64
func bindUnitDefaultFlyHeight(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultFlyHeight()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DefaultMoveSpeed -> Unit.DefaultMoveSpeed() float64
func bindUnitDefaultMoveSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultMoveSpeed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DefaultPropWindow -> Unit.DefaultPropWindow() float64
func bindUnitDefaultPropWindow(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultPropWindow()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DefaultTurnSpeed -> Unit.DefaultTurnSpeed() float64
func bindUnitDefaultTurnSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultTurnSpeed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DropItem -> Unit.DropItem(n int) bool
func bindUnitDropItem(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	res := recv.DropItem(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_ExperienceSuspended -> Unit.ExperienceSuspended() bool
func bindUnitExperienceSuspended(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.ExperienceSuspended()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Facing -> Unit.Facing() Angle
func bindUnitFacing(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Facing()
	L.Push(angleToLua(res))
	return 1
}

// Unit_FlyHeight -> Unit.FlyHeight() float64
func bindUnitFlyHeight(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.FlyHeight()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_FoodMade -> Unit.FoodMade() int
func bindUnitFoodMade(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.FoodMade()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_FoodUsed -> Unit.FoodUsed() int
func bindUnitFoodUsed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.FoodUsed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_GiveItemTo -> Unit.GiveItemTo(n int, to Unit) bool
func bindUnitGiveItemTo(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	a1 := argUnit(L, 3)
	res := recv.GiveItemTo(a0, a1)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_HeroLevel -> Unit.HeroLevel() int
func bindUnitHeroLevel(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.HeroLevel()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_HeroXP -> Unit.HeroXP() int
func bindUnitHeroXP(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.HeroXP()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_ID -> Unit.ID() uint32
func bindUnitID(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.ID()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_InRange -> Unit.InRange(other Unit, distance float64) bool
func bindUnitInRange(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argUnit(L, 2)
	a1 := float64(L.CheckNumber(3))
	res := recv.InRange(a0, a1)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_InRangeOf -> Unit.InRangeOf(point Vec2, distance float64) bool
func bindUnitInRangeOf(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argVec2(L, 2)
	a1 := float64(L.CheckNumber(3))
	res := recv.InRangeOf(a0, a1)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Intelligence -> Unit.Intelligence() int
func bindUnitIntelligence(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Intelligence()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_InventorySize -> Unit.InventorySize() int
func bindUnitInventorySize(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.InventorySize()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Invulnerable -> Unit.Invulnerable() bool
func bindUnitInvulnerable(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Invulnerable()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_IsHidden -> Unit.IsHidden() bool
func bindUnitIsHidden(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.IsHidden()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_ItemCount -> Unit.ItemCount() int
func bindUnitItemCount(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.ItemCount()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_ItemInSlot -> Unit.ItemInSlot(n int) Item
func bindUnitItemInSlot(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	res := recv.ItemInSlot(a0)
	L.Push(handleToLua(L, res))
	return 1
}

// Unit_Kill -> Unit.Kill()
func bindUnitKill(L *lua.LState) int {
	recv := argUnit(L, 1)
	recv.Kill()
	return 0
}

// Unit_LearnSkill -> Unit.LearnSkill(skill int) bool
func bindUnitLearnSkill(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	res := recv.LearnSkill(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Level -> Unit.Level() int
func bindUnitLevel(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Level()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Life -> Unit.Life() float64
func bindUnitLife(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Life()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_LifePercent -> Unit.LifePercent() float64
func bindUnitLifePercent(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.LifePercent()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_ManaPercent -> Unit.ManaPercent() float64
func bindUnitManaPercent(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.ManaPercent()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_MaxLife -> Unit.MaxLife() float64
func bindUnitMaxLife(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.MaxLife()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_MaxMana -> Unit.MaxMana() float64
func bindUnitMaxMana(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.MaxMana()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_ModifySkillPoints -> Unit.ModifySkillPoints(delta int) bool
func bindUnitModifySkillPoints(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	res := recv.ModifySkillPoints(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_MoveSpeed -> Unit.MoveSpeed() float64
func bindUnitMoveSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.MoveSpeed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Name -> Unit.Name() string
func bindUnitName(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Name()
	L.Push(lua.LString(res))
	return 1
}

// Unit_Paused -> Unit.Paused() bool
func bindUnitPaused(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Paused()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_PointValue -> Unit.PointValue() int
func bindUnitPointValue(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.PointValue()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Position -> Unit.Position() Vec2
func bindUnitPosition(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Position()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Unit_PropWindow -> Unit.PropWindow() float64
func bindUnitPropWindow(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.PropWindow()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_RallyPoint -> Unit.RallyPoint() Vec2
func bindUnitRallyPoint(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.RallyPoint()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Unit_RallyUnit -> Unit.RallyUnit() Unit
func bindUnitRallyUnit(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.RallyUnit()
	L.Push(handleToLua(L, res))
	return 1
}

// Unit_Remove -> Unit.Remove()
func bindUnitRemove(L *lua.LState) int {
	recv := argUnit(L, 1)
	recv.Remove()
	return 0
}

// Unit_RemoveAllBuffs -> Unit.RemoveAllBuffs() int
func bindUnitRemoveAllBuffs(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.RemoveAllBuffs()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_SetAcquireRange -> Unit.SetAcquireRange(v float64)
func bindUnitSetAcquireRange(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetAcquireRange(a0)
	return 0
}

// Unit_SetAgility -> Unit.SetAgility(v int)
func bindUnitSetAgility(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetAgility(a0)
	return 0
}

// Unit_SetFacing -> Unit.SetFacing(a Angle)
func bindUnitSetFacing(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argAngle(L, 2)
	recv.SetFacing(a0)
	return 0
}

// Unit_SetFlyHeight -> Unit.SetFlyHeight(newHeight, ratePerSec float64)
func bindUnitSetFlyHeight(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	a1 := float64(L.CheckNumber(3))
	recv.SetFlyHeight(a0, a1)
	return 0
}

// Unit_SetHeroLevel -> Unit.SetHeroLevel(level int)
func bindUnitSetHeroLevel(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetHeroLevel(a0)
	return 0
}

// Unit_SetHeroXP -> Unit.SetHeroXP(xp int)
func bindUnitSetHeroXP(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetHeroXP(a0)
	return 0
}

// Unit_SetIntelligence -> Unit.SetIntelligence(v int)
func bindUnitSetIntelligence(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetIntelligence(a0)
	return 0
}

// Unit_SetInvulnerable -> Unit.SetInvulnerable(on bool)
func bindUnitSetInvulnerable(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckBool(2)
	recv.SetInvulnerable(a0)
	return 0
}

// Unit_SetLife -> Unit.SetLife(v float64)
func bindUnitSetLife(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetLife(a0)
	return 0
}

// Unit_SetMaxLife -> Unit.SetMaxLife(v float64)
func bindUnitSetMaxLife(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetMaxLife(a0)
	return 0
}

// Unit_SetMaxMana -> Unit.SetMaxMana(v float64)
func bindUnitSetMaxMana(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetMaxMana(a0)
	return 0
}

// Unit_SetMoveSpeed -> Unit.SetMoveSpeed(v float64)
func bindUnitSetMoveSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetMoveSpeed(a0)
	return 0
}

// Unit_SetName -> Unit.SetName(name string)
func bindUnitSetName(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckString(2)
	recv.SetName(a0)
	return 0
}

// Unit_SetPaused -> Unit.SetPaused(paused bool)
func bindUnitSetPaused(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckBool(2)
	recv.SetPaused(a0)
	return 0
}

// Unit_SetPosition -> Unit.SetPosition(pos Vec2)
func bindUnitSetPosition(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argVec2(L, 2)
	recv.SetPosition(a0)
	return 0
}

// Unit_SetPropWindow -> Unit.SetPropWindow(radians float64)
func bindUnitSetPropWindow(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetPropWindow(a0)
	return 0
}

// Unit_SetStrength -> Unit.SetStrength(v int)
func bindUnitSetStrength(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetStrength(a0)
	return 0
}

// Unit_SetTurnSpeed -> Unit.SetTurnSpeed(radPerSec float64)
func bindUnitSetTurnSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetTurnSpeed(a0)
	return 0
}

// Unit_SetUserData -> Unit.SetUserData(v int)
func bindUnitSetUserData(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetUserData(a0)
	return 0
}

// Unit_Show -> Unit.Show(show bool)
func bindUnitShow(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckBool(2)
	recv.Show(a0)
	return 0
}

// Unit_SkillPoints -> Unit.SkillPoints() int
func bindUnitSkillPoints(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.SkillPoints()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Strength -> Unit.Strength() int
func bindUnitStrength(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Strength()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_SuspendExperience -> Unit.SuspendExperience(suspend bool)
func bindUnitSuspendExperience(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckBool(2)
	recv.SuspendExperience(a0)
	return 0
}

// Unit_TurnSpeed -> Unit.TurnSpeed() float64
func bindUnitTurnSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.TurnSpeed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_UserData -> Unit.UserData() int
func bindUnitUserData(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.UserData()
	L.Push(lua.LNumber(res))
	return 1
}

// Vec2_Add -> Vec2.Add(o Vec2) Vec2
func bindVec2Add(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argVec2(L, 2)
	res := recv.Add(a0)
	L.Push(vec2ToLua(L, res))
	return 1
}

// Vec2_AngleTo -> Vec2.AngleTo(o Vec2) Angle
func bindVec2AngleTo(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argVec2(L, 2)
	res := recv.AngleTo(a0)
	L.Push(angleToLua(res))
	return 1
}

// Vec2_DistanceTo -> Vec2.DistanceTo(o Vec2) float64
func bindVec2DistanceTo(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argVec2(L, 2)
	res := recv.DistanceTo(a0)
	L.Push(lua.LNumber(res))
	return 1
}

// Vec2_Polar -> Vec2.Polar(a Angle, dist float64) Vec2
func bindVec2Polar(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argAngle(L, 2)
	a1 := float64(L.CheckNumber(3))
	res := recv.Polar(a0, a1)
	L.Push(vec2ToLua(L, res))
	return 1
}
