// Code generated by jassgen; DO NOT EDIT.
// Lua binding descriptors derived from api-manifest.json (G2.7).
// VM registration is wired in M5; these descriptors are the contract.

package luabind

// Binding is one Lua global -> canonical Go symbol descriptor.
type Binding struct {
	LuaName     string
	Package     string
	Symbol      string
	GoSignature string
}

// Bindings is the core API surface (litd/api + litd/api/helpers).
var Bindings = []Binding{
	{LuaName: "PolledWait", Package: "litd/api/helpers", Symbol: "PolledWait", GoSignature: "(seconds float64)"},
	{LuaName: "Unit_Paused", Package: "litd/api", Symbol: "Unit.Paused", GoSignature: "() bool"},
	{LuaName: "Unit_SetLife", Package: "litd/api", Symbol: "Unit.SetLife", GoSignature: "(v float64)"},
	{LuaName: "Unit_SetPaused", Package: "litd/api", Symbol: "Unit.SetPaused", GoSignature: "(paused bool)"},
	{LuaName: "Unit_SetPosition", Package: "litd/api", Symbol: "Unit.SetPosition", GoSignature: "(pos Vec2)"},
}

// AIBindings is the AI-domain surface (litd/ai, R-EXEC-3 isolated).
var AIBindings = []Binding{
	{LuaName: "UnitCount", Package: "litd/ai", Symbol: "UnitCount", GoSignature: "(unitTypeID int) int"},
}
