// Code generated by jassgen; DO NOT EDIT.
// Lua binding dispatch derived from api-manifest.json (#267): 254 of 409 mapped
// verbs bound. The rest need handle/enum/slice/Game/variadic marshaling not yet
// emitted by the generator and are intentionally unbound (no silent drop).

package luabind

import (
	lua "github.com/yuin/gopher-lua"
)

// registerGenerated installs the generated value/handle-verb globals on L.
// These verbs need no game: value types are pure and a handle/Player userdata
// self-carries its *Game. Game-receiver verbs install via registerGameBound.
func registerGenerated(L *lua.LState) {
	L.SetGlobal("Ability_DecLevel", L.NewFunction(bindAbilityDecLevel))
	L.SetGlobal("Ability_Field", L.NewFunction(bindAbilityField))
	L.SetGlobal("Ability_IncLevel", L.NewFunction(bindAbilityIncLevel))
	L.SetGlobal("Ability_Level", L.NewFunction(bindAbilityLevel))
	L.SetGlobal("Ability_SetField", L.NewFunction(bindAbilitySetField))
	L.SetGlobal("Ability_SetLevel", L.NewFunction(bindAbilitySetLevel))
	L.SetGlobal("Angle_Degrees", L.NewFunction(bindAngleDegrees))
	L.SetGlobal("Camera_Field", L.NewFunction(bindCameraField))
	L.SetGlobal("Camera_Follow", L.NewFunction(bindCameraFollow))
	L.SetGlobal("Camera_Pan", L.NewFunction(bindCameraPan))
	L.SetGlobal("Camera_SetBounds", L.NewFunction(bindCameraSetBounds))
	L.SetGlobal("Camera_SetField", L.NewFunction(bindCameraSetField))
	L.SetGlobal("Camera_Shake", L.NewFunction(bindCameraShake))
	L.SetGlobal("Camera_StopFollow", L.NewFunction(bindCameraStopFollow))
	L.SetGlobal("DamageEvent_SetAmount", L.NewFunction(bindDamageEventSetAmount))
	L.SetGlobal("Destructable_Dead", L.NewFunction(bindDestructableDead))
	L.SetGlobal("Destructable_Invulnerable", L.NewFunction(bindDestructableInvulnerable))
	L.SetGlobal("Destructable_Kill", L.NewFunction(bindDestructableKill))
	L.SetGlobal("Destructable_Life", L.NewFunction(bindDestructableLife))
	L.SetGlobal("Destructable_MaxLife", L.NewFunction(bindDestructableMaxLife))
	L.SetGlobal("Destructable_PlayAnimation", L.NewFunction(bindDestructablePlayAnimation))
	L.SetGlobal("Destructable_Resurrect", L.NewFunction(bindDestructableResurrect))
	L.SetGlobal("Destructable_SetInvulnerable", L.NewFunction(bindDestructableSetInvulnerable))
	L.SetGlobal("Destructable_SetLife", L.NewFunction(bindDestructableSetLife))
	L.SetGlobal("Effect_Destroy", L.NewFunction(bindEffectDestroy))
	L.SetGlobal("Effect_SetColor", L.NewFunction(bindEffectSetColor))
	L.SetGlobal("Effect_SetPosition", L.NewFunction(bindEffectSetPosition))
	L.SetGlobal("Effect_SetScale", L.NewFunction(bindEffectSetScale))
	L.SetGlobal("Event_Damage", L.NewFunction(bindEventDamage))
	L.SetGlobal("Event_KillingUnit", L.NewFunction(bindEventKillingUnit))
	L.SetGlobal("Event_Player", L.NewFunction(bindEventPlayer))
	L.SetGlobal("Event_Region", L.NewFunction(bindEventRegion))
	L.SetGlobal("Event_Source", L.NewFunction(bindEventSource))
	L.SetGlobal("Event_Subscription", L.NewFunction(bindEventSubscription))
	L.SetGlobal("Event_Target", L.NewFunction(bindEventTarget))
	L.SetGlobal("Event_Unit", L.NewFunction(bindEventUnit))
	L.SetGlobal("Force_AddAllPlayers", L.NewFunction(bindForceAddAllPlayers))
	L.SetGlobal("Force_AddPlayer", L.NewFunction(bindForceAddPlayer))
	L.SetGlobal("Force_Clear", L.NewFunction(bindForceClear))
	L.SetGlobal("Force_Contains", L.NewFunction(bindForceContains))
	L.SetGlobal("Force_Players", L.NewFunction(bindForcePlayers))
	L.SetGlobal("Force_RemovePlayer", L.NewFunction(bindForceRemovePlayer))
	L.SetGlobal("Item_Charges", L.NewFunction(bindItemCharges))
	L.SetGlobal("Item_Position", L.NewFunction(bindItemPosition))
	L.SetGlobal("Item_Remove", L.NewFunction(bindItemRemove))
	L.SetGlobal("Item_SetCharges", L.NewFunction(bindItemSetCharges))
	L.SetGlobal("Item_Type", L.NewFunction(bindItemType))
	L.SetGlobal("Player_AllianceWith", L.NewFunction(bindPlayerAllianceWith))
	L.SetGlobal("Player_Color", L.NewFunction(bindPlayerColor))
	L.SetGlobal("Player_Controller", L.NewFunction(bindPlayerController))
	L.SetGlobal("Player_Gold", L.NewFunction(bindPlayerGold))
	L.SetGlobal("Player_Handicap", L.NewFunction(bindPlayerHandicap))
	L.SetGlobal("Player_HandicapDamage", L.NewFunction(bindPlayerHandicapDamage))
	L.SetGlobal("Player_HandicapReviveTime", L.NewFunction(bindPlayerHandicapReviveTime))
	L.SetGlobal("Player_HandicapXP", L.NewFunction(bindPlayerHandicapXP))
	L.SetGlobal("Player_IsAlly", L.NewFunction(bindPlayerIsAlly))
	L.SetGlobal("Player_IsEnemy", L.NewFunction(bindPlayerIsEnemy))
	L.SetGlobal("Player_Name", L.NewFunction(bindPlayerName))
	L.SetGlobal("Player_Race", L.NewFunction(bindPlayerRace))
	L.SetGlobal("Player_SetAllianceFlag", L.NewFunction(bindPlayerSetAllianceFlag))
	L.SetGlobal("Player_SetColor", L.NewFunction(bindPlayerSetColor))
	L.SetGlobal("Player_SetController", L.NewFunction(bindPlayerSetController))
	L.SetGlobal("Player_SetGold", L.NewFunction(bindPlayerSetGold))
	L.SetGlobal("Player_SetHandicap", L.NewFunction(bindPlayerSetHandicap))
	L.SetGlobal("Player_SetHandicapDamage", L.NewFunction(bindPlayerSetHandicapDamage))
	L.SetGlobal("Player_SetHandicapReviveTime", L.NewFunction(bindPlayerSetHandicapReviveTime))
	L.SetGlobal("Player_SetHandicapXP", L.NewFunction(bindPlayerSetHandicapXP))
	L.SetGlobal("Player_SetName", L.NewFunction(bindPlayerSetName))
	L.SetGlobal("Player_SetRace", L.NewFunction(bindPlayerSetRace))
	L.SetGlobal("Player_SetStartLocation", L.NewFunction(bindPlayerSetStartLocation))
	L.SetGlobal("Player_SetTaxRate", L.NewFunction(bindPlayerSetTaxRate))
	L.SetGlobal("Player_SetTeam", L.NewFunction(bindPlayerSetTeam))
	L.SetGlobal("Player_Slot", L.NewFunction(bindPlayerSlot))
	L.SetGlobal("Player_StartLocation", L.NewFunction(bindPlayerStartLocation))
	L.SetGlobal("Player_TaxRate", L.NewFunction(bindPlayerTaxRate))
	L.SetGlobal("Player_Team", L.NewFunction(bindPlayerTeam))
	L.SetGlobal("Rect_Center", L.NewFunction(bindRectCenter))
	L.SetGlobal("Rect_Contains", L.NewFunction(bindRectContains))
	L.SetGlobal("Rect_Height", L.NewFunction(bindRectHeight))
	L.SetGlobal("Rect_Max", L.NewFunction(bindRectMax))
	L.SetGlobal("Rect_Min", L.NewFunction(bindRectMin))
	L.SetGlobal("Rect_Offset", L.NewFunction(bindRectOffset))
	L.SetGlobal("Rect_Width", L.NewFunction(bindRectWidth))
	L.SetGlobal("Region_AddCell", L.NewFunction(bindRegionAddCell))
	L.SetGlobal("Region_AddRect", L.NewFunction(bindRegionAddRect))
	L.SetGlobal("Region_Contains", L.NewFunction(bindRegionContains))
	L.SetGlobal("Region_ContainsUnit", L.NewFunction(bindRegionContainsUnit))
	L.SetGlobal("Region_Remove", L.NewFunction(bindRegionRemove))
	L.SetGlobal("Region_RemoveCell", L.NewFunction(bindRegionRemoveCell))
	L.SetGlobal("Region_RemoveRect", L.NewFunction(bindRegionRemoveRect))
	L.SetGlobal("Sound_Play", L.NewFunction(bindSoundPlay))
	L.SetGlobal("Sound_PlayAt", L.NewFunction(bindSoundPlayAt))
	L.SetGlobal("Sound_PlayOn", L.NewFunction(bindSoundPlayOn))
	L.SetGlobal("Sound_SetPitch", L.NewFunction(bindSoundSetPitch))
	L.SetGlobal("Sound_SetVolume", L.NewFunction(bindSoundSetVolume))
	L.SetGlobal("Sound_Stop", L.NewFunction(bindSoundStop))
	L.SetGlobal("Storage_Clear", L.NewFunction(bindStorageClear))
	L.SetGlobal("Storage_SetInt", L.NewFunction(bindStorageSetInt))
	L.SetGlobal("Timer_Elapsed", L.NewFunction(bindTimerElapsed))
	L.SetGlobal("Timer_Pause", L.NewFunction(bindTimerPause))
	L.SetGlobal("Timer_Remaining", L.NewFunction(bindTimerRemaining))
	L.SetGlobal("Timer_Resume", L.NewFunction(bindTimerResume))
	L.SetGlobal("Timer_Stop", L.NewFunction(bindTimerStop))
	L.SetGlobal("Timer_Timeout", L.NewFunction(bindTimerTimeout))
	L.SetGlobal("UnitSet_Add", L.NewFunction(bindUnitSetAdd))
	L.SetGlobal("UnitSet_Clear", L.NewFunction(bindUnitSetClear))
	L.SetGlobal("UnitSet_Contains", L.NewFunction(bindUnitSetContains))
	L.SetGlobal("UnitSet_Count", L.NewFunction(bindUnitSetCount))
	L.SetGlobal("UnitSet_Remove", L.NewFunction(bindUnitSetRemove))
	L.SetGlobal("UnitSet_Units", L.NewFunction(bindUnitSetUnits))
	L.SetGlobal("Unit_AcquireRange", L.NewFunction(bindUnitAcquireRange))
	L.SetGlobal("Unit_AddAbility", L.NewFunction(bindUnitAddAbility))
	L.SetGlobal("Unit_AddExperience", L.NewFunction(bindUnitAddExperience))
	L.SetGlobal("Unit_AddItem", L.NewFunction(bindUnitAddItem))
	L.SetGlobal("Unit_AddItemByType", L.NewFunction(bindUnitAddItemByType))
	L.SetGlobal("Unit_Agility", L.NewFunction(bindUnitAgility))
	L.SetGlobal("Unit_Alive", L.NewFunction(bindUnitAlive))
	L.SetGlobal("Unit_Armor", L.NewFunction(bindUnitArmor))
	L.SetGlobal("Unit_BuffCount", L.NewFunction(bindUnitBuffCount))
	L.SetGlobal("Unit_CollisionSize", L.NewFunction(bindUnitCollisionSize))
	L.SetGlobal("Unit_CurrentOrder", L.NewFunction(bindUnitCurrentOrder))
	L.SetGlobal("Unit_Damage", L.NewFunction(bindUnitDamage))
	L.SetGlobal("Unit_DefaultAcquireRange", L.NewFunction(bindUnitDefaultAcquireRange))
	L.SetGlobal("Unit_DefaultFlyHeight", L.NewFunction(bindUnitDefaultFlyHeight))
	L.SetGlobal("Unit_DefaultMoveSpeed", L.NewFunction(bindUnitDefaultMoveSpeed))
	L.SetGlobal("Unit_DefaultPropWindow", L.NewFunction(bindUnitDefaultPropWindow))
	L.SetGlobal("Unit_DefaultTurnSpeed", L.NewFunction(bindUnitDefaultTurnSpeed))
	L.SetGlobal("Unit_DropItem", L.NewFunction(bindUnitDropItem))
	L.SetGlobal("Unit_ExperienceSuspended", L.NewFunction(bindUnitExperienceSuspended))
	L.SetGlobal("Unit_Facing", L.NewFunction(bindUnitFacing))
	L.SetGlobal("Unit_FlyHeight", L.NewFunction(bindUnitFlyHeight))
	L.SetGlobal("Unit_FoodMade", L.NewFunction(bindUnitFoodMade))
	L.SetGlobal("Unit_FoodUsed", L.NewFunction(bindUnitFoodUsed))
	L.SetGlobal("Unit_GiveItemTo", L.NewFunction(bindUnitGiveItemTo))
	L.SetGlobal("Unit_HasBuff", L.NewFunction(bindUnitHasBuff))
	L.SetGlobal("Unit_HeroLevel", L.NewFunction(bindUnitHeroLevel))
	L.SetGlobal("Unit_HeroXP", L.NewFunction(bindUnitHeroXP))
	L.SetGlobal("Unit_ID", L.NewFunction(bindUnitID))
	L.SetGlobal("Unit_InRange", L.NewFunction(bindUnitInRange))
	L.SetGlobal("Unit_InRangeOf", L.NewFunction(bindUnitInRangeOf))
	L.SetGlobal("Unit_Intelligence", L.NewFunction(bindUnitIntelligence))
	L.SetGlobal("Unit_InventorySize", L.NewFunction(bindUnitInventorySize))
	L.SetGlobal("Unit_Invulnerable", L.NewFunction(bindUnitInvulnerable))
	L.SetGlobal("Unit_IsHidden", L.NewFunction(bindUnitIsHidden))
	L.SetGlobal("Unit_IsRace", L.NewFunction(bindUnitIsRace))
	L.SetGlobal("Unit_IsType", L.NewFunction(bindUnitIsType))
	L.SetGlobal("Unit_ItemCount", L.NewFunction(bindUnitItemCount))
	L.SetGlobal("Unit_ItemInSlot", L.NewFunction(bindUnitItemInSlot))
	L.SetGlobal("Unit_Kill", L.NewFunction(bindUnitKill))
	L.SetGlobal("Unit_LearnSkill", L.NewFunction(bindUnitLearnSkill))
	L.SetGlobal("Unit_Level", L.NewFunction(bindUnitLevel))
	L.SetGlobal("Unit_Life", L.NewFunction(bindUnitLife))
	L.SetGlobal("Unit_LifePercent", L.NewFunction(bindUnitLifePercent))
	L.SetGlobal("Unit_ManaPercent", L.NewFunction(bindUnitManaPercent))
	L.SetGlobal("Unit_MaxLife", L.NewFunction(bindUnitMaxLife))
	L.SetGlobal("Unit_MaxMana", L.NewFunction(bindUnitMaxMana))
	L.SetGlobal("Unit_ModifySkillPoints", L.NewFunction(bindUnitModifySkillPoints))
	L.SetGlobal("Unit_MoveSpeed", L.NewFunction(bindUnitMoveSpeed))
	L.SetGlobal("Unit_Name", L.NewFunction(bindUnitName))
	L.SetGlobal("Unit_Order", L.NewFunction(bindUnitOrder))
	L.SetGlobal("Unit_OwnedBy", L.NewFunction(bindUnitOwnedBy))
	L.SetGlobal("Unit_Owner", L.NewFunction(bindUnitOwner))
	L.SetGlobal("Unit_Paused", L.NewFunction(bindUnitPaused))
	L.SetGlobal("Unit_PointValue", L.NewFunction(bindUnitPointValue))
	L.SetGlobal("Unit_Position", L.NewFunction(bindUnitPosition))
	L.SetGlobal("Unit_PropWindow", L.NewFunction(bindUnitPropWindow))
	L.SetGlobal("Unit_Race", L.NewFunction(bindUnitRace))
	L.SetGlobal("Unit_RallyPoint", L.NewFunction(bindUnitRallyPoint))
	L.SetGlobal("Unit_RallyUnit", L.NewFunction(bindUnitRallyUnit))
	L.SetGlobal("Unit_Remove", L.NewFunction(bindUnitRemove))
	L.SetGlobal("Unit_RemoveAbility", L.NewFunction(bindUnitRemoveAbility))
	L.SetGlobal("Unit_RemoveAllBuffs", L.NewFunction(bindUnitRemoveAllBuffs))
	L.SetGlobal("Unit_RemoveBuff", L.NewFunction(bindUnitRemoveBuff))
	L.SetGlobal("Unit_SetAcquireRange", L.NewFunction(bindUnitSetAcquireRange))
	L.SetGlobal("Unit_SetAgility", L.NewFunction(bindUnitSetAgility))
	L.SetGlobal("Unit_SetFacing", L.NewFunction(bindUnitSetFacing))
	L.SetGlobal("Unit_SetFlyHeight", L.NewFunction(bindUnitSetFlyHeight))
	L.SetGlobal("Unit_SetHeroLevel", L.NewFunction(bindUnitSetHeroLevel))
	L.SetGlobal("Unit_SetHeroXP", L.NewFunction(bindUnitSetHeroXP))
	L.SetGlobal("Unit_SetIntelligence", L.NewFunction(bindUnitSetIntelligence))
	L.SetGlobal("Unit_SetInvulnerable", L.NewFunction(bindUnitSetInvulnerable))
	L.SetGlobal("Unit_SetLife", L.NewFunction(bindUnitSetLife))
	L.SetGlobal("Unit_SetMana", L.NewFunction(bindUnitSetMana))
	L.SetGlobal("Unit_SetMaxLife", L.NewFunction(bindUnitSetMaxLife))
	L.SetGlobal("Unit_SetMaxMana", L.NewFunction(bindUnitSetMaxMana))
	L.SetGlobal("Unit_SetMoveSpeed", L.NewFunction(bindUnitSetMoveSpeed))
	L.SetGlobal("Unit_SetName", L.NewFunction(bindUnitSetName))
	L.SetGlobal("Unit_SetOwner", L.NewFunction(bindUnitSetOwner))
	L.SetGlobal("Unit_SetPaused", L.NewFunction(bindUnitSetPaused))
	L.SetGlobal("Unit_SetPosition", L.NewFunction(bindUnitSetPosition))
	L.SetGlobal("Unit_SetPropWindow", L.NewFunction(bindUnitSetPropWindow))
	L.SetGlobal("Unit_SetStrength", L.NewFunction(bindUnitSetStrength))
	L.SetGlobal("Unit_SetTurnSpeed", L.NewFunction(bindUnitSetTurnSpeed))
	L.SetGlobal("Unit_SetUserData", L.NewFunction(bindUnitSetUserData))
	L.SetGlobal("Unit_ShareVision", L.NewFunction(bindUnitShareVision))
	L.SetGlobal("Unit_Show", L.NewFunction(bindUnitShow))
	L.SetGlobal("Unit_SkillPoints", L.NewFunction(bindUnitSkillPoints))
	L.SetGlobal("Unit_Strength", L.NewFunction(bindUnitStrength))
	L.SetGlobal("Unit_SuspendExperience", L.NewFunction(bindUnitSuspendExperience))
	L.SetGlobal("Unit_TurnSpeed", L.NewFunction(bindUnitTurnSpeed))
	L.SetGlobal("Unit_Type", L.NewFunction(bindUnitType))
	L.SetGlobal("Unit_UseItem", L.NewFunction(bindUnitUseItem))
	L.SetGlobal("Unit_UserData", L.NewFunction(bindUnitUserData))
	L.SetGlobal("Unit_VisibleTo", L.NewFunction(bindUnitVisibleTo))
	L.SetGlobal("Vec2_Add", L.NewFunction(bindVec2Add))
	L.SetGlobal("Vec2_AngleTo", L.NewFunction(bindVec2AngleTo))
	L.SetGlobal("Vec2_DistanceTo", L.NewFunction(bindVec2DistanceTo))
	L.SetGlobal("Vec2_Polar", L.NewFunction(bindVec2Polar))
}

// registerGameBound installs the generated Game-receiver verb globals on L,
// each bound through b (the implicit game receiver; the script passes no game
// arg). gameBinder is defined in register.go so this file imports only lua.
func registerGameBound(L *lua.LState, b gameBinder) {
	L.SetGlobal("Game_AIDifficulty", L.NewFunction(b.bindGameAIDifficulty))
	L.SetGlobal("Game_AddSpecialEffect", L.NewFunction(b.bindGameAddSpecialEffect))
	L.SetGlobal("Game_Allies", L.NewFunction(b.bindGameAllies))
	L.SetGlobal("Game_CommandAI", L.NewFunction(b.bindGameCommandAI))
	L.SetGlobal("Game_CreateForce", L.NewFunction(b.bindGameCreateForce))
	L.SetGlobal("Game_CreateItem", L.NewFunction(b.bindGameCreateItem))
	L.SetGlobal("Game_CreateSound", L.NewFunction(b.bindGameCreateSound))
	L.SetGlobal("Game_CreateUnit", L.NewFunction(b.bindGameCreateUnit))
	L.SetGlobal("Game_Defeat", L.NewFunction(b.bindGameDefeat))
	L.SetGlobal("Game_EndMatch", L.NewFunction(b.bindGameEndMatch))
	L.SetGlobal("Game_Enemies", L.NewFunction(b.bindGameEnemies))
	L.SetGlobal("Game_FogEnabled", L.NewFunction(b.bindGameFogEnabled))
	L.SetGlobal("Game_FogMaskEnabled", L.NewFunction(b.bindGameFogMaskEnabled))
	L.SetGlobal("Game_FogStateAt", L.NewFunction(b.bindGameFogStateAt))
	L.SetGlobal("Game_IsVisibleTo", L.NewFunction(b.bindGameIsVisibleTo))
	L.SetGlobal("Game_MapFlag", L.NewFunction(b.bindGameMapFlag))
	L.SetGlobal("Game_NeutralHostile", L.NewFunction(b.bindGameNeutralHostile))
	L.SetGlobal("Game_NeutralPassive", L.NewFunction(b.bindGameNeutralPassive))
	L.SetGlobal("Game_NewRegion", L.NewFunction(b.bindGameNewRegion))
	L.SetGlobal("Game_NewUnitSet", L.NewFunction(b.bindGameNewUnitSet))
	L.SetGlobal("Game_Pause", L.NewFunction(b.bindGamePause))
	L.SetGlobal("Game_PauseAI", L.NewFunction(b.bindGamePauseAI))
	L.SetGlobal("Game_PlayMusic", L.NewFunction(b.bindGamePlayMusic))
	L.SetGlobal("Game_Player", L.NewFunction(b.bindGamePlayer))
	L.SetGlobal("Game_RandomAngle", L.NewFunction(b.bindGameRandomAngle))
	L.SetGlobal("Game_RandomFloat", L.NewFunction(b.bindGameRandomFloat))
	L.SetGlobal("Game_RandomInt", L.NewFunction(b.bindGameRandomInt))
	L.SetGlobal("Game_RandomPointIn", L.NewFunction(b.bindGameRandomPointIn))
	L.SetGlobal("Game_SetChannelVolume", L.NewFunction(b.bindGameSetChannelVolume))
	L.SetGlobal("Game_SetFogEnabled", L.NewFunction(b.bindGameSetFogEnabled))
	L.SetGlobal("Game_SetFogMaskEnabled", L.NewFunction(b.bindGameSetFogMaskEnabled))
	L.SetGlobal("Game_SetMusicVolume", L.NewFunction(b.bindGameSetMusicVolume))
	L.SetGlobal("Game_SetRandomSeed", L.NewFunction(b.bindGameSetRandomSeed))
	L.SetGlobal("Game_SetSpeed", L.NewFunction(b.bindGameSetSpeed))
	L.SetGlobal("Game_SetTimeOfDay", L.NewFunction(b.bindGameSetTimeOfDay))
	L.SetGlobal("Game_SetTimeOfDayScale", L.NewFunction(b.bindGameSetTimeOfDayScale))
	L.SetGlobal("Game_StartLocation", L.NewFunction(b.bindGameStartLocation))
	L.SetGlobal("Game_StopMusic", L.NewFunction(b.bindGameStopMusic))
	L.SetGlobal("Game_Storage", L.NewFunction(b.bindGameStorage))
	L.SetGlobal("Game_SuspendTimeOfDay", L.NewFunction(b.bindGameSuspendTimeOfDay))
	L.SetGlobal("Game_Teams", L.NewFunction(b.bindGameTeams))
	L.SetGlobal("Game_TerrainHeight", L.NewFunction(b.bindGameTerrainHeight))
	L.SetGlobal("Game_TimeOfDay", L.NewFunction(b.bindGameTimeOfDay))
	L.SetGlobal("Game_TimeOfDayScale", L.NewFunction(b.bindGameTimeOfDayScale))
	L.SetGlobal("Game_Victory", L.NewFunction(b.bindGameVictory))
	L.SetGlobal("Game_WorldBounds", L.NewFunction(b.bindGameWorldBounds))
}

// Ability_DecLevel -> Ability.DecLevel() int
func bindAbilityDecLevel(L *lua.LState) int {
	recv := argAbility(L, 1)
	res := recv.DecLevel()
	L.Push(lua.LNumber(res))
	return 1
}

// Ability_Field -> Ability.Field(field AbilityField) float64
func bindAbilityField(L *lua.LState) int {
	recv := argAbility(L, 1)
	a0 := argAbilityField(L, 2)
	res := recv.Field(a0)
	L.Push(lua.LNumber(res))
	return 1
}

// Ability_IncLevel -> Ability.IncLevel() int
func bindAbilityIncLevel(L *lua.LState) int {
	recv := argAbility(L, 1)
	res := recv.IncLevel()
	L.Push(lua.LNumber(res))
	return 1
}

// Ability_Level -> Ability.Level() int
func bindAbilityLevel(L *lua.LState) int {
	recv := argAbility(L, 1)
	res := recv.Level()
	L.Push(lua.LNumber(res))
	return 1
}

// Ability_SetField -> Ability.SetField(field AbilityField, value float64)
func bindAbilitySetField(L *lua.LState) int {
	recv := argAbility(L, 1)
	a0 := argAbilityField(L, 2)
	a1 := float64(L.CheckNumber(3))
	recv.SetField(a0, a1)
	return 0
}

// Ability_SetLevel -> Ability.SetLevel(level int)
func bindAbilitySetLevel(L *lua.LState) int {
	recv := argAbility(L, 1)
	a0 := L.CheckInt(2)
	recv.SetLevel(a0)
	return 0
}

// Angle_Degrees -> Angle.Degrees() float64
func bindAngleDegrees(L *lua.LState) int {
	recv := argAngle(L, 1)
	res := recv.Degrees()
	L.Push(lua.LNumber(res))
	return 1
}

// Camera_Field -> Camera.Field(f CameraField) float64
func bindCameraField(L *lua.LState) int {
	recv := argCamera(L, 1)
	a0 := argCameraField(L, 2)
	res := recv.Field(a0)
	L.Push(lua.LNumber(res))
	return 1
}

// Camera_Follow -> Camera.Follow(u Unit)
func bindCameraFollow(L *lua.LState) int {
	recv := argCamera(L, 1)
	a0 := argUnit(L, 2)
	recv.Follow(a0)
	return 0
}

// Camera_Pan -> Camera.Pan(pos Vec2, opts ...PanOption)
func bindCameraPan(L *lua.LState) int {
	recv := argCamera(L, 1)
	if L.GetTop() > 2 {
		L.RaiseError("Camera_Pan: options arguments are not yet bound from Lua (#267)")
		return 0
	}
	a0 := argVec2(L, 2)
	recv.Pan(a0)
	return 0
}

// Camera_SetBounds -> Camera.SetBounds(r Rect)
func bindCameraSetBounds(L *lua.LState) int {
	recv := argCamera(L, 1)
	a0 := argRect(L, 2)
	recv.SetBounds(a0)
	return 0
}

// Camera_SetField -> Camera.SetField(f CameraField, v float64)
func bindCameraSetField(L *lua.LState) int {
	recv := argCamera(L, 1)
	a0 := argCameraField(L, 2)
	a1 := float64(L.CheckNumber(3))
	recv.SetField(a0, a1)
	return 0
}

// Camera_Shake -> Camera.Shake(magnitude float64)
func bindCameraShake(L *lua.LState) int {
	recv := argCamera(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.Shake(a0)
	return 0
}

// Camera_StopFollow -> Camera.StopFollow()
func bindCameraStopFollow(L *lua.LState) int {
	recv := argCamera(L, 1)
	recv.StopFollow()
	return 0
}

// DamageEvent_SetAmount -> DamageEvent.SetAmount(v float64)
func bindDamageEventSetAmount(L *lua.LState) int {
	recv := argDamageEvent(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetAmount(a0)
	return 0
}

// Destructable_Dead -> Destructable.Dead() bool
func bindDestructableDead(L *lua.LState) int {
	recv := argDestructable(L, 1)
	res := recv.Dead()
	L.Push(lua.LBool(res))
	return 1
}

// Destructable_Invulnerable -> Destructable.Invulnerable() bool
func bindDestructableInvulnerable(L *lua.LState) int {
	recv := argDestructable(L, 1)
	res := recv.Invulnerable()
	L.Push(lua.LBool(res))
	return 1
}

// Destructable_Kill -> Destructable.Kill()
func bindDestructableKill(L *lua.LState) int {
	recv := argDestructable(L, 1)
	recv.Kill()
	return 0
}

// Destructable_Life -> Destructable.Life() int
func bindDestructableLife(L *lua.LState) int {
	recv := argDestructable(L, 1)
	res := recv.Life()
	L.Push(lua.LNumber(res))
	return 1
}

// Destructable_MaxLife -> Destructable.MaxLife() int
func bindDestructableMaxLife(L *lua.LState) int {
	recv := argDestructable(L, 1)
	res := recv.MaxLife()
	L.Push(lua.LNumber(res))
	return 1
}

// Destructable_PlayAnimation -> Destructable.PlayAnimation(name string)
func bindDestructablePlayAnimation(L *lua.LState) int {
	recv := argDestructable(L, 1)
	a0 := L.CheckString(2)
	recv.PlayAnimation(a0)
	return 0
}

// Destructable_Resurrect -> Destructable.Resurrect()
func bindDestructableResurrect(L *lua.LState) int {
	recv := argDestructable(L, 1)
	recv.Resurrect()
	return 0
}

// Destructable_SetInvulnerable -> Destructable.SetInvulnerable(b bool)
func bindDestructableSetInvulnerable(L *lua.LState) int {
	recv := argDestructable(L, 1)
	a0 := L.CheckBool(2)
	recv.SetInvulnerable(a0)
	return 0
}

// Destructable_SetLife -> Destructable.SetLife(v int)
func bindDestructableSetLife(L *lua.LState) int {
	recv := argDestructable(L, 1)
	a0 := L.CheckInt(2)
	recv.SetLife(a0)
	return 0
}

// Effect_Destroy -> Effect.Destroy()
func bindEffectDestroy(L *lua.LState) int {
	recv := argEffect(L, 1)
	recv.Destroy()
	return 0
}

// Effect_SetColor -> Effect.SetColor(r, g, b uint8)
func bindEffectSetColor(L *lua.LState) int {
	recv := argEffect(L, 1)
	a0 := uint8(L.CheckInt(2))
	a1 := uint8(L.CheckInt(3))
	a2 := uint8(L.CheckInt(4))
	recv.SetColor(a0, a1, a2)
	return 0
}

// Effect_SetPosition -> Effect.SetPosition(pos Vec2)
func bindEffectSetPosition(L *lua.LState) int {
	recv := argEffect(L, 1)
	a0 := argVec2(L, 2)
	recv.SetPosition(a0)
	return 0
}

// Effect_SetScale -> Effect.SetScale(scale float64)
func bindEffectSetScale(L *lua.LState) int {
	recv := argEffect(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetScale(a0)
	return 0
}

// Event_Damage -> Event.Damage() float64
func bindEventDamage(L *lua.LState) int {
	recv := argEvent(L, 1)
	res := recv.Damage()
	L.Push(lua.LNumber(res))
	return 1
}

// Event_KillingUnit -> Event.KillingUnit() Unit
func bindEventKillingUnit(L *lua.LState) int {
	recv := argEvent(L, 1)
	res := recv.KillingUnit()
	L.Push(pushHandle(L, res))
	return 1
}

// Event_Player -> Event.Player() Player
func bindEventPlayer(L *lua.LState) int {
	recv := argEvent(L, 1)
	res := recv.Player()
	L.Push(pushHandle(L, res))
	return 1
}

// Event_Region -> Event.Region() Region
func bindEventRegion(L *lua.LState) int {
	recv := argEvent(L, 1)
	res := recv.Region()
	L.Push(pushHandle(L, res))
	return 1
}

// Event_Source -> Event.Source() Unit
func bindEventSource(L *lua.LState) int {
	recv := argEvent(L, 1)
	res := recv.Source()
	L.Push(pushHandle(L, res))
	return 1
}

// Event_Subscription -> Event.Subscription() Subscription
func bindEventSubscription(L *lua.LState) int {
	recv := argEvent(L, 1)
	res := recv.Subscription()
	L.Push(pushHandle(L, res))
	return 1
}

// Event_Target -> Event.Target() Unit
func bindEventTarget(L *lua.LState) int {
	recv := argEvent(L, 1)
	res := recv.Target()
	L.Push(pushHandle(L, res))
	return 1
}

// Event_Unit -> Event.Unit() Unit
func bindEventUnit(L *lua.LState) int {
	recv := argEvent(L, 1)
	res := recv.Unit()
	L.Push(pushHandle(L, res))
	return 1
}

// Force_AddAllPlayers -> Force.AddAllPlayers()
func bindForceAddAllPlayers(L *lua.LState) int {
	recv := argForce(L, 1)
	recv.AddAllPlayers()
	return 0
}

// Force_AddPlayer -> Force.AddPlayer(p Player)
func bindForceAddPlayer(L *lua.LState) int {
	recv := argForce(L, 1)
	a0 := argPlayer(L, 2)
	recv.AddPlayer(a0)
	return 0
}

// Force_Clear -> Force.Clear()
func bindForceClear(L *lua.LState) int {
	recv := argForce(L, 1)
	recv.Clear()
	return 0
}

// Force_Contains -> Force.Contains(p Player) bool
func bindForceContains(L *lua.LState) int {
	recv := argForce(L, 1)
	a0 := argPlayer(L, 2)
	res := recv.Contains(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Force_Players -> Force.Players() []Player
func bindForcePlayers(L *lua.LState) int {
	recv := argForce(L, 1)
	res := recv.Players()
	L.Push(handleSliceToLua(L, res))
	return 1
}

// Force_RemovePlayer -> Force.RemovePlayer(p Player)
func bindForceRemovePlayer(L *lua.LState) int {
	recv := argForce(L, 1)
	a0 := argPlayer(L, 2)
	recv.RemovePlayer(a0)
	return 0
}

// Game_AIDifficulty -> Game.AIDifficulty(p Player) Difficulty
func (b gameBinder) bindGameAIDifficulty(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	res := b.g.AIDifficulty(a0)
	L.Push(lua.LNumber(res))
	return 1
}

// Game_AddSpecialEffect -> Game.AddSpecialEffect(model string, pos Vec2) Effect
func (b gameBinder) bindGameAddSpecialEffect(L *lua.LState) int {
	a0 := L.CheckString(1)
	a1 := argVec2(L, 2)
	res := b.g.AddSpecialEffect(a0, a1)
	L.Push(pushHandle(L, res))
	return 1
}

// Game_Allies -> Game.Allies(p Player) []Player
func (b gameBinder) bindGameAllies(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	res := b.g.Allies(a0)
	L.Push(handleSliceToLua(L, res))
	return 1
}

// Game_CommandAI -> Game.CommandAI(p Player, command, data int)
func (b gameBinder) bindGameCommandAI(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	a1 := L.CheckInt(2)
	a2 := L.CheckInt(3)
	b.g.CommandAI(a0, a1, a2)
	return 0
}

// Game_CreateForce -> Game.CreateForce() Force
func (b gameBinder) bindGameCreateForce(L *lua.LState) int {
	res := b.g.CreateForce()
	L.Push(pushHandle(L, res))
	return 1
}

// Game_CreateItem -> Game.CreateItem(typ ItemType, pos Vec2) Item
func (b gameBinder) bindGameCreateItem(L *lua.LState) int {
	a0 := argItemType(L, 1)
	a1 := argVec2(L, 2)
	res := b.g.CreateItem(a0, a1)
	L.Push(pushHandle(L, res))
	return 1
}

// Game_CreateSound -> Game.CreateSound(cue string) Sound
func (b gameBinder) bindGameCreateSound(L *lua.LState) int {
	a0 := L.CheckString(1)
	res := b.g.CreateSound(a0)
	L.Push(pushHandle(L, res))
	return 1
}

// Game_CreateUnit -> Game.CreateUnit(owner Player, typ UnitType, pos Vec2, facing Angle) Unit
func (b gameBinder) bindGameCreateUnit(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	a1 := argUnitType(L, 2)
	a2 := argVec2(L, 3)
	a3 := argAngle(L, 4)
	res := b.g.CreateUnit(a0, a1, a2, a3)
	L.Push(pushHandle(L, res))
	return 1
}

// Game_Defeat -> Game.Defeat(p Player, msg string)
func (b gameBinder) bindGameDefeat(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	a1 := L.CheckString(2)
	b.g.Defeat(a0, a1)
	return 0
}

// Game_EndMatch -> Game.EndMatch()
func (b gameBinder) bindGameEndMatch(L *lua.LState) int {
	b.g.EndMatch()
	return 0
}

// Game_Enemies -> Game.Enemies(p Player) []Player
func (b gameBinder) bindGameEnemies(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	res := b.g.Enemies(a0)
	L.Push(handleSliceToLua(L, res))
	return 1
}

// Game_FogEnabled -> Game.FogEnabled() bool
func (b gameBinder) bindGameFogEnabled(L *lua.LState) int {
	res := b.g.FogEnabled()
	L.Push(lua.LBool(res))
	return 1
}

// Game_FogMaskEnabled -> Game.FogMaskEnabled() bool
func (b gameBinder) bindGameFogMaskEnabled(L *lua.LState) int {
	res := b.g.FogMaskEnabled()
	L.Push(lua.LBool(res))
	return 1
}

// Game_FogStateAt -> Game.FogStateAt(p Player, pos Vec2) FogState
func (b gameBinder) bindGameFogStateAt(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	a1 := argVec2(L, 2)
	res := b.g.FogStateAt(a0, a1)
	L.Push(lua.LNumber(res))
	return 1
}

// Game_IsVisibleTo -> Game.IsVisibleTo(p Player, pos Vec2) bool
func (b gameBinder) bindGameIsVisibleTo(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	a1 := argVec2(L, 2)
	res := b.g.IsVisibleTo(a0, a1)
	L.Push(lua.LBool(res))
	return 1
}

// Game_MapFlag -> Game.MapFlag(f MapFlag) bool
func (b gameBinder) bindGameMapFlag(L *lua.LState) int {
	a0 := argMapFlag(L, 1)
	res := b.g.MapFlag(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Game_NeutralHostile -> Game.NeutralHostile() Player
func (b gameBinder) bindGameNeutralHostile(L *lua.LState) int {
	res := b.g.NeutralHostile()
	L.Push(pushHandle(L, res))
	return 1
}

// Game_NeutralPassive -> Game.NeutralPassive() Player
func (b gameBinder) bindGameNeutralPassive(L *lua.LState) int {
	res := b.g.NeutralPassive()
	L.Push(pushHandle(L, res))
	return 1
}

// Game_NewRegion -> Game.NewRegion() Region
func (b gameBinder) bindGameNewRegion(L *lua.LState) int {
	res := b.g.NewRegion()
	L.Push(pushHandle(L, res))
	return 1
}

// Game_NewUnitSet -> Game.NewUnitSet() *UnitSet
func (b gameBinder) bindGameNewUnitSet(L *lua.LState) int {
	res := b.g.NewUnitSet()
	L.Push(handleToLua(L, res))
	return 1
}

// Game_Pause -> Game.Pause()
func (b gameBinder) bindGamePause(L *lua.LState) int {
	b.g.Pause()
	return 0
}

// Game_PauseAI -> Game.PauseAI(p Player, paused bool)
func (b gameBinder) bindGamePauseAI(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	a1 := L.CheckBool(2)
	b.g.PauseAI(a0, a1)
	return 0
}

// Game_PlayMusic -> Game.PlayMusic(cue string)
func (b gameBinder) bindGamePlayMusic(L *lua.LState) int {
	a0 := L.CheckString(1)
	b.g.PlayMusic(a0)
	return 0
}

// Game_Player -> Game.Player(slot int) Player
func (b gameBinder) bindGamePlayer(L *lua.LState) int {
	a0 := L.CheckInt(1)
	res := b.g.Player(a0)
	L.Push(pushHandle(L, res))
	return 1
}

// Game_RandomAngle -> Game.RandomAngle() Angle
func (b gameBinder) bindGameRandomAngle(L *lua.LState) int {
	res := b.g.RandomAngle()
	L.Push(angleToLua(res))
	return 1
}

// Game_RandomFloat -> Game.RandomFloat() float64
func (b gameBinder) bindGameRandomFloat(L *lua.LState) int {
	res := b.g.RandomFloat()
	L.Push(lua.LNumber(res))
	return 1
}

// Game_RandomInt -> Game.RandomInt(min, max int) int
func (b gameBinder) bindGameRandomInt(L *lua.LState) int {
	a0 := L.CheckInt(1)
	a1 := L.CheckInt(2)
	res := b.g.RandomInt(a0, a1)
	L.Push(lua.LNumber(res))
	return 1
}

// Game_RandomPointIn -> Game.RandomPointIn(rc Rect) Vec2
func (b gameBinder) bindGameRandomPointIn(L *lua.LState) int {
	a0 := argRect(L, 1)
	res := b.g.RandomPointIn(a0)
	L.Push(vec2ToLua(L, res))
	return 1
}

// Game_SetChannelVolume -> Game.SetChannelVolume(ch SoundChannel, v float64)
func (b gameBinder) bindGameSetChannelVolume(L *lua.LState) int {
	a0 := argSoundChannel(L, 1)
	a1 := float64(L.CheckNumber(2))
	b.g.SetChannelVolume(a0, a1)
	return 0
}

// Game_SetFogEnabled -> Game.SetFogEnabled(on bool)
func (b gameBinder) bindGameSetFogEnabled(L *lua.LState) int {
	a0 := L.CheckBool(1)
	b.g.SetFogEnabled(a0)
	return 0
}

// Game_SetFogMaskEnabled -> Game.SetFogMaskEnabled(on bool)
func (b gameBinder) bindGameSetFogMaskEnabled(L *lua.LState) int {
	a0 := L.CheckBool(1)
	b.g.SetFogMaskEnabled(a0)
	return 0
}

// Game_SetMusicVolume -> Game.SetMusicVolume(v float64)
func (b gameBinder) bindGameSetMusicVolume(L *lua.LState) int {
	a0 := float64(L.CheckNumber(1))
	b.g.SetMusicVolume(a0)
	return 0
}

// Game_SetRandomSeed -> Game.SetRandomSeed(seed int64)
func (b gameBinder) bindGameSetRandomSeed(L *lua.LState) int {
	a0 := L.CheckInt64(1)
	b.g.SetRandomSeed(a0)
	return 0
}

// Game_SetSpeed -> Game.SetSpeed(s GameSpeed)
func (b gameBinder) bindGameSetSpeed(L *lua.LState) int {
	a0 := argGameSpeed(L, 1)
	b.g.SetSpeed(a0)
	return 0
}

// Game_SetTimeOfDay -> Game.SetTimeOfDay(h float64)
func (b gameBinder) bindGameSetTimeOfDay(L *lua.LState) int {
	a0 := float64(L.CheckNumber(1))
	b.g.SetTimeOfDay(a0)
	return 0
}

// Game_SetTimeOfDayScale -> Game.SetTimeOfDayScale(s float64)
func (b gameBinder) bindGameSetTimeOfDayScale(L *lua.LState) int {
	a0 := float64(L.CheckNumber(1))
	b.g.SetTimeOfDayScale(a0)
	return 0
}

// Game_StartLocation -> Game.StartLocation(i int) Vec2
func (b gameBinder) bindGameStartLocation(L *lua.LState) int {
	a0 := L.CheckInt(1)
	res := b.g.StartLocation(a0)
	L.Push(vec2ToLua(L, res))
	return 1
}

// Game_StopMusic -> Game.StopMusic()
func (b gameBinder) bindGameStopMusic(L *lua.LState) int {
	b.g.StopMusic()
	return 0
}

// Game_Storage -> Game.Storage() *Storage
func (b gameBinder) bindGameStorage(L *lua.LState) int {
	res := b.g.Storage()
	L.Push(handleToLua(L, res))
	return 1
}

// Game_SuspendTimeOfDay -> Game.SuspendTimeOfDay(suspended bool)
func (b gameBinder) bindGameSuspendTimeOfDay(L *lua.LState) int {
	a0 := L.CheckBool(1)
	b.g.SuspendTimeOfDay(a0)
	return 0
}

// Game_Teams -> Game.Teams() int
func (b gameBinder) bindGameTeams(L *lua.LState) int {
	res := b.g.Teams()
	L.Push(lua.LNumber(res))
	return 1
}

// Game_TerrainHeight -> Game.TerrainHeight(p Vec2) float64
func (b gameBinder) bindGameTerrainHeight(L *lua.LState) int {
	a0 := argVec2(L, 1)
	res := b.g.TerrainHeight(a0)
	L.Push(lua.LNumber(res))
	return 1
}

// Game_TimeOfDay -> Game.TimeOfDay() float64
func (b gameBinder) bindGameTimeOfDay(L *lua.LState) int {
	res := b.g.TimeOfDay()
	L.Push(lua.LNumber(res))
	return 1
}

// Game_TimeOfDayScale -> Game.TimeOfDayScale() float64
func (b gameBinder) bindGameTimeOfDayScale(L *lua.LState) int {
	res := b.g.TimeOfDayScale()
	L.Push(lua.LNumber(res))
	return 1
}

// Game_Victory -> Game.Victory(p Player)
func (b gameBinder) bindGameVictory(L *lua.LState) int {
	a0 := argPlayer(L, 1)
	b.g.Victory(a0)
	return 0
}

// Game_WorldBounds -> Game.WorldBounds() Rect
func (b gameBinder) bindGameWorldBounds(L *lua.LState) int {
	res := b.g.WorldBounds()
	L.Push(rectToLua(L, res))
	return 1
}

// Item_Charges -> Item.Charges() int
func bindItemCharges(L *lua.LState) int {
	recv := argItem(L, 1)
	res := recv.Charges()
	L.Push(lua.LNumber(res))
	return 1
}

// Item_Position -> Item.Position() Vec2
func bindItemPosition(L *lua.LState) int {
	recv := argItem(L, 1)
	res := recv.Position()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Item_Remove -> Item.Remove()
func bindItemRemove(L *lua.LState) int {
	recv := argItem(L, 1)
	recv.Remove()
	return 0
}

// Item_SetCharges -> Item.SetCharges(n int)
func bindItemSetCharges(L *lua.LState) int {
	recv := argItem(L, 1)
	a0 := L.CheckInt(2)
	recv.SetCharges(a0)
	return 0
}

// Item_Type -> Item.Type() ItemType
func bindItemType(L *lua.LState) int {
	recv := argItem(L, 1)
	res := recv.Type()
	L.Push(pushHandle(L, res))
	return 1
}

// Player_AllianceWith -> Player.AllianceWith(other Player) AllianceFlags
func bindPlayerAllianceWith(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := argPlayer(L, 2)
	res := recv.AllianceWith(a0)
	L.Push(lua.LNumber(res))
	return 1
}

// Player_Color -> Player.Color() int
func bindPlayerColor(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.Color()
	L.Push(lua.LNumber(res))
	return 1
}

// Player_Controller -> Player.Controller() Controller
func bindPlayerController(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.Controller()
	L.Push(lua.LNumber(res))
	return 1
}

// Player_Gold -> Player.Gold() int
func bindPlayerGold(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.Gold()
	L.Push(lua.LNumber(res))
	return 1
}

// Player_Handicap -> Player.Handicap() float64
func bindPlayerHandicap(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.Handicap()
	L.Push(lua.LNumber(res))
	return 1
}

// Player_HandicapDamage -> Player.HandicapDamage() float64
func bindPlayerHandicapDamage(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.HandicapDamage()
	L.Push(lua.LNumber(res))
	return 1
}

// Player_HandicapReviveTime -> Player.HandicapReviveTime() float64
func bindPlayerHandicapReviveTime(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.HandicapReviveTime()
	L.Push(lua.LNumber(res))
	return 1
}

// Player_HandicapXP -> Player.HandicapXP() float64
func bindPlayerHandicapXP(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.HandicapXP()
	L.Push(lua.LNumber(res))
	return 1
}

// Player_IsAlly -> Player.IsAlly(other Player) bool
func bindPlayerIsAlly(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := argPlayer(L, 2)
	res := recv.IsAlly(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Player_IsEnemy -> Player.IsEnemy(other Player) bool
func bindPlayerIsEnemy(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := argPlayer(L, 2)
	res := recv.IsEnemy(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Player_Name -> Player.Name() string
func bindPlayerName(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.Name()
	L.Push(lua.LString(res))
	return 1
}

// Player_Race -> Player.Race() Race
func bindPlayerRace(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.Race()
	L.Push(lua.LNumber(res))
	return 1
}

// Player_SetAllianceFlag -> Player.SetAllianceFlag(other Player, flag AllianceFlags, on bool)
func bindPlayerSetAllianceFlag(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := argPlayer(L, 2)
	a1 := argAllianceFlags(L, 3)
	a2 := L.CheckBool(4)
	recv.SetAllianceFlag(a0, a1, a2)
	return 0
}

// Player_SetColor -> Player.SetColor(c int)
func bindPlayerSetColor(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := L.CheckInt(2)
	recv.SetColor(a0)
	return 0
}

// Player_SetController -> Player.SetController(c Controller)
func bindPlayerSetController(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := argController(L, 2)
	recv.SetController(a0)
	return 0
}

// Player_SetGold -> Player.SetGold(v int)
func bindPlayerSetGold(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := L.CheckInt(2)
	recv.SetGold(a0)
	return 0
}

// Player_SetHandicap -> Player.SetHandicap(v float64)
func bindPlayerSetHandicap(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetHandicap(a0)
	return 0
}

// Player_SetHandicapDamage -> Player.SetHandicapDamage(v float64)
func bindPlayerSetHandicapDamage(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetHandicapDamage(a0)
	return 0
}

// Player_SetHandicapReviveTime -> Player.SetHandicapReviveTime(v float64)
func bindPlayerSetHandicapReviveTime(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetHandicapReviveTime(a0)
	return 0
}

// Player_SetHandicapXP -> Player.SetHandicapXP(v float64)
func bindPlayerSetHandicapXP(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetHandicapXP(a0)
	return 0
}

// Player_SetName -> Player.SetName(s string)
func bindPlayerSetName(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := L.CheckString(2)
	recv.SetName(a0)
	return 0
}

// Player_SetRace -> Player.SetRace(r Race)
func bindPlayerSetRace(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := argRace(L, 2)
	recv.SetRace(a0)
	return 0
}

// Player_SetStartLocation -> Player.SetStartLocation(loc Vec2)
func bindPlayerSetStartLocation(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := argVec2(L, 2)
	recv.SetStartLocation(a0)
	return 0
}

// Player_SetTaxRate -> Player.SetTaxRate(other Player, resource int, rate float64)
func bindPlayerSetTaxRate(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := argPlayer(L, 2)
	a1 := L.CheckInt(3)
	a2 := float64(L.CheckNumber(4))
	recv.SetTaxRate(a0, a1, a2)
	return 0
}

// Player_SetTeam -> Player.SetTeam(t int)
func bindPlayerSetTeam(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := L.CheckInt(2)
	recv.SetTeam(a0)
	return 0
}

// Player_Slot -> Player.Slot() int
func bindPlayerSlot(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.Slot()
	L.Push(lua.LNumber(res))
	return 1
}

// Player_StartLocation -> Player.StartLocation() Vec2
func bindPlayerStartLocation(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.StartLocation()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Player_TaxRate -> Player.TaxRate(other Player, resource int) float64
func bindPlayerTaxRate(L *lua.LState) int {
	recv := argPlayer(L, 1)
	a0 := argPlayer(L, 2)
	a1 := L.CheckInt(3)
	res := recv.TaxRate(a0, a1)
	L.Push(lua.LNumber(res))
	return 1
}

// Player_Team -> Player.Team() int
func bindPlayerTeam(L *lua.LState) int {
	recv := argPlayer(L, 1)
	res := recv.Team()
	L.Push(lua.LNumber(res))
	return 1
}

// Rect_Center -> Rect.Center() Vec2
func bindRectCenter(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Center()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Rect_Contains -> Rect.Contains(p Vec2) bool
func bindRectContains(L *lua.LState) int {
	recv := argRect(L, 1)
	a0 := argVec2(L, 2)
	res := recv.Contains(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Rect_Height -> Rect.Height() float64
func bindRectHeight(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Height()
	L.Push(lua.LNumber(res))
	return 1
}

// Rect_Max -> Rect.Max() Vec2
func bindRectMax(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Max()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Rect_Min -> Rect.Min() Vec2
func bindRectMin(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Min()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Rect_Offset -> Rect.Offset(d Vec2) Rect
func bindRectOffset(L *lua.LState) int {
	recv := argRect(L, 1)
	a0 := argVec2(L, 2)
	res := recv.Offset(a0)
	L.Push(rectToLua(L, res))
	return 1
}

// Rect_Width -> Rect.Width() float64
func bindRectWidth(L *lua.LState) int {
	recv := argRect(L, 1)
	res := recv.Width()
	L.Push(lua.LNumber(res))
	return 1
}

// Region_AddCell -> Region.AddCell(p Vec2)
func bindRegionAddCell(L *lua.LState) int {
	recv := argRegion(L, 1)
	a0 := argVec2(L, 2)
	recv.AddCell(a0)
	return 0
}

// Region_AddRect -> Region.AddRect(rc Rect)
func bindRegionAddRect(L *lua.LState) int {
	recv := argRegion(L, 1)
	a0 := argRect(L, 2)
	recv.AddRect(a0)
	return 0
}

// Region_Contains -> Region.Contains(p Vec2) bool
func bindRegionContains(L *lua.LState) int {
	recv := argRegion(L, 1)
	a0 := argVec2(L, 2)
	res := recv.Contains(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Region_ContainsUnit -> Region.ContainsUnit(u Unit) bool
func bindRegionContainsUnit(L *lua.LState) int {
	recv := argRegion(L, 1)
	a0 := argUnit(L, 2)
	res := recv.ContainsUnit(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Region_Remove -> Region.Remove()
func bindRegionRemove(L *lua.LState) int {
	recv := argRegion(L, 1)
	recv.Remove()
	return 0
}

// Region_RemoveCell -> Region.RemoveCell(p Vec2)
func bindRegionRemoveCell(L *lua.LState) int {
	recv := argRegion(L, 1)
	a0 := argVec2(L, 2)
	recv.RemoveCell(a0)
	return 0
}

// Region_RemoveRect -> Region.RemoveRect(rc Rect)
func bindRegionRemoveRect(L *lua.LState) int {
	recv := argRegion(L, 1)
	a0 := argRect(L, 2)
	recv.RemoveRect(a0)
	return 0
}

// Sound_Play -> Sound.Play()
func bindSoundPlay(L *lua.LState) int {
	recv := argSound(L, 1)
	recv.Play()
	return 0
}

// Sound_PlayAt -> Sound.PlayAt(pos Vec2, z float64)
func bindSoundPlayAt(L *lua.LState) int {
	recv := argSound(L, 1)
	a0 := argVec2(L, 2)
	a1 := float64(L.CheckNumber(3))
	recv.PlayAt(a0, a1)
	return 0
}

// Sound_PlayOn -> Sound.PlayOn(u Unit)
func bindSoundPlayOn(L *lua.LState) int {
	recv := argSound(L, 1)
	a0 := argUnit(L, 2)
	recv.PlayOn(a0)
	return 0
}

// Sound_SetPitch -> Sound.SetPitch(p float64)
func bindSoundSetPitch(L *lua.LState) int {
	recv := argSound(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetPitch(a0)
	return 0
}

// Sound_SetVolume -> Sound.SetVolume(v float64)
func bindSoundSetVolume(L *lua.LState) int {
	recv := argSound(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetVolume(a0)
	return 0
}

// Sound_Stop -> Sound.Stop()
func bindSoundStop(L *lua.LState) int {
	recv := argSound(L, 1)
	recv.Stop()
	return 0
}

// Storage_Clear -> Storage.Clear()
func bindStorageClear(L *lua.LState) int {
	recv := argStorage(L, 1)
	recv.Clear()
	return 0
}

// Storage_SetInt -> Storage.SetInt(category, key string, v int)
func bindStorageSetInt(L *lua.LState) int {
	recv := argStorage(L, 1)
	a0 := L.CheckString(2)
	a1 := L.CheckString(3)
	a2 := L.CheckInt(4)
	recv.SetInt(a0, a1, a2)
	return 0
}

// Timer_Elapsed -> Timer.Elapsed() time.Duration
func bindTimerElapsed(L *lua.LState) int {
	recv := argTimer(L, 1)
	res := recv.Elapsed()
	L.Push(lua.LNumber(res.Seconds()))
	return 1
}

// Timer_Pause -> Timer.Pause()
func bindTimerPause(L *lua.LState) int {
	recv := argTimer(L, 1)
	recv.Pause()
	return 0
}

// Timer_Remaining -> Timer.Remaining() time.Duration
func bindTimerRemaining(L *lua.LState) int {
	recv := argTimer(L, 1)
	res := recv.Remaining()
	L.Push(lua.LNumber(res.Seconds()))
	return 1
}

// Timer_Resume -> Timer.Resume()
func bindTimerResume(L *lua.LState) int {
	recv := argTimer(L, 1)
	recv.Resume()
	return 0
}

// Timer_Stop -> Timer.Stop()
func bindTimerStop(L *lua.LState) int {
	recv := argTimer(L, 1)
	recv.Stop()
	return 0
}

// Timer_Timeout -> Timer.Timeout() time.Duration
func bindTimerTimeout(L *lua.LState) int {
	recv := argTimer(L, 1)
	res := recv.Timeout()
	L.Push(lua.LNumber(res.Seconds()))
	return 1
}

// UnitSet_Add -> UnitSet.Add(u Unit)
func bindUnitSetAdd(L *lua.LState) int {
	recv := argUnitSet(L, 1)
	a0 := argUnit(L, 2)
	recv.Add(a0)
	return 0
}

// UnitSet_Clear -> UnitSet.Clear()
func bindUnitSetClear(L *lua.LState) int {
	recv := argUnitSet(L, 1)
	recv.Clear()
	return 0
}

// UnitSet_Contains -> UnitSet.Contains(u Unit) bool
func bindUnitSetContains(L *lua.LState) int {
	recv := argUnitSet(L, 1)
	a0 := argUnit(L, 2)
	res := recv.Contains(a0)
	L.Push(lua.LBool(res))
	return 1
}

// UnitSet_Count -> UnitSet.Count() int
func bindUnitSetCount(L *lua.LState) int {
	recv := argUnitSet(L, 1)
	res := recv.Count()
	L.Push(lua.LNumber(res))
	return 1
}

// UnitSet_Remove -> UnitSet.Remove(u Unit)
func bindUnitSetRemove(L *lua.LState) int {
	recv := argUnitSet(L, 1)
	a0 := argUnit(L, 2)
	recv.Remove(a0)
	return 0
}

// UnitSet_Units -> UnitSet.Units() []Unit
func bindUnitSetUnits(L *lua.LState) int {
	recv := argUnitSet(L, 1)
	res := recv.Units()
	L.Push(handleSliceToLua(L, res))
	return 1
}

// Unit_AcquireRange -> Unit.AcquireRange() float64
func bindUnitAcquireRange(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.AcquireRange()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_AddAbility -> Unit.AddAbility(ref AbilityRef) Ability
func bindUnitAddAbility(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argAbilityRef(L, 2)
	res := recv.AddAbility(a0)
	L.Push(pushHandle(L, res))
	return 1
}

// Unit_AddExperience -> Unit.AddExperience(xp int)
func bindUnitAddExperience(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.AddExperience(a0)
	return 0
}

// Unit_AddItem -> Unit.AddItem(it Item) bool
func bindUnitAddItem(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argItem(L, 2)
	res := recv.AddItem(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_AddItemByType -> Unit.AddItemByType(typ ItemType, opts ...SlotOption) Item
func bindUnitAddItemByType(L *lua.LState) int {
	recv := argUnit(L, 1)
	if L.GetTop() > 2 {
		L.RaiseError("Unit_AddItemByType: options arguments are not yet bound from Lua (#267)")
		return 0
	}
	a0 := argItemType(L, 2)
	res := recv.AddItemByType(a0)
	L.Push(pushHandle(L, res))
	return 1
}

// Unit_Agility -> Unit.Agility() int
func bindUnitAgility(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Agility()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Alive -> Unit.Alive() bool
func bindUnitAlive(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Alive()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Armor -> Unit.Armor() float64
func bindUnitArmor(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Armor()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_BuffCount -> Unit.BuffCount() int
func bindUnitBuffCount(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.BuffCount()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_CollisionSize -> Unit.CollisionSize() float64
func bindUnitCollisionSize(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.CollisionSize()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_CurrentOrder -> Unit.CurrentOrder() Order
func bindUnitCurrentOrder(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.CurrentOrder()
	L.Push(pushHandle(L, res))
	return 1
}

// Unit_Damage -> Unit.Damage(target Widget, amount float64, opts ...DamageOption) bool
func bindUnitDamage(L *lua.LState) int {
	recv := argUnit(L, 1)
	if L.GetTop() > 3 {
		L.RaiseError("Unit_Damage: options arguments are not yet bound from Lua (#267)")
		return 0
	}
	a0 := argWidget(L, 2)
	a1 := float64(L.CheckNumber(3))
	res := recv.Damage(a0, a1)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_DefaultAcquireRange -> Unit.DefaultAcquireRange() float64
func bindUnitDefaultAcquireRange(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultAcquireRange()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DefaultFlyHeight -> Unit.DefaultFlyHeight() float64
func bindUnitDefaultFlyHeight(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultFlyHeight()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DefaultMoveSpeed -> Unit.DefaultMoveSpeed() float64
func bindUnitDefaultMoveSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultMoveSpeed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DefaultPropWindow -> Unit.DefaultPropWindow() float64
func bindUnitDefaultPropWindow(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultPropWindow()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DefaultTurnSpeed -> Unit.DefaultTurnSpeed() float64
func bindUnitDefaultTurnSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.DefaultTurnSpeed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_DropItem -> Unit.DropItem(n int) bool
func bindUnitDropItem(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	res := recv.DropItem(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_ExperienceSuspended -> Unit.ExperienceSuspended() bool
func bindUnitExperienceSuspended(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.ExperienceSuspended()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Facing -> Unit.Facing() Angle
func bindUnitFacing(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Facing()
	L.Push(angleToLua(res))
	return 1
}

// Unit_FlyHeight -> Unit.FlyHeight() float64
func bindUnitFlyHeight(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.FlyHeight()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_FoodMade -> Unit.FoodMade() int
func bindUnitFoodMade(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.FoodMade()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_FoodUsed -> Unit.FoodUsed() int
func bindUnitFoodUsed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.FoodUsed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_GiveItemTo -> Unit.GiveItemTo(n int, to Unit) bool
func bindUnitGiveItemTo(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	a1 := argUnit(L, 3)
	res := recv.GiveItemTo(a0, a1)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_HasBuff -> Unit.HasBuff(typ BuffType) bool
func bindUnitHasBuff(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argBuffType(L, 2)
	res := recv.HasBuff(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_HeroLevel -> Unit.HeroLevel() int
func bindUnitHeroLevel(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.HeroLevel()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_HeroXP -> Unit.HeroXP() int
func bindUnitHeroXP(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.HeroXP()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_ID -> Unit.ID() uint32
func bindUnitID(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.ID()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_InRange -> Unit.InRange(other Unit, distance float64) bool
func bindUnitInRange(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argUnit(L, 2)
	a1 := float64(L.CheckNumber(3))
	res := recv.InRange(a0, a1)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_InRangeOf -> Unit.InRangeOf(point Vec2, distance float64) bool
func bindUnitInRangeOf(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argVec2(L, 2)
	a1 := float64(L.CheckNumber(3))
	res := recv.InRangeOf(a0, a1)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Intelligence -> Unit.Intelligence() int
func bindUnitIntelligence(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Intelligence()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_InventorySize -> Unit.InventorySize() int
func bindUnitInventorySize(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.InventorySize()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Invulnerable -> Unit.Invulnerable() bool
func bindUnitInvulnerable(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Invulnerable()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_IsHidden -> Unit.IsHidden() bool
func bindUnitIsHidden(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.IsHidden()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_IsRace -> Unit.IsRace(r Race) bool
func bindUnitIsRace(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argRace(L, 2)
	res := recv.IsRace(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_IsType -> Unit.IsType(class UnitClass) bool
func bindUnitIsType(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argUnitClass(L, 2)
	res := recv.IsType(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_ItemCount -> Unit.ItemCount() int
func bindUnitItemCount(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.ItemCount()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_ItemInSlot -> Unit.ItemInSlot(n int) Item
func bindUnitItemInSlot(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	res := recv.ItemInSlot(a0)
	L.Push(pushHandle(L, res))
	return 1
}

// Unit_Kill -> Unit.Kill()
func bindUnitKill(L *lua.LState) int {
	recv := argUnit(L, 1)
	recv.Kill()
	return 0
}

// Unit_LearnSkill -> Unit.LearnSkill(skill int) bool
func bindUnitLearnSkill(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	res := recv.LearnSkill(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Level -> Unit.Level() int
func bindUnitLevel(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Level()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Life -> Unit.Life() float64
func bindUnitLife(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Life()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_LifePercent -> Unit.LifePercent() float64
func bindUnitLifePercent(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.LifePercent()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_ManaPercent -> Unit.ManaPercent() float64
func bindUnitManaPercent(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.ManaPercent()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_MaxLife -> Unit.MaxLife() float64
func bindUnitMaxLife(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.MaxLife()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_MaxMana -> Unit.MaxMana() float64
func bindUnitMaxMana(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.MaxMana()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_ModifySkillPoints -> Unit.ModifySkillPoints(delta int) bool
func bindUnitModifySkillPoints(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	res := recv.ModifySkillPoints(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_MoveSpeed -> Unit.MoveSpeed() float64
func bindUnitMoveSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.MoveSpeed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Name -> Unit.Name() string
func bindUnitName(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Name()
	L.Push(lua.LString(res))
	return 1
}

// Unit_Order -> Unit.Order(ord Order, target OrderTarget) bool
func bindUnitOrder(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argOrder(L, 2)
	a1 := argOrderTarget(L, 3)
	res := recv.Order(a0, a1)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_OwnedBy -> Unit.OwnedBy(p Player) bool
func bindUnitOwnedBy(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argPlayer(L, 2)
	res := recv.OwnedBy(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_Owner -> Unit.Owner() Player
func bindUnitOwner(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Owner()
	L.Push(pushHandle(L, res))
	return 1
}

// Unit_Paused -> Unit.Paused() bool
func bindUnitPaused(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Paused()
	L.Push(lua.LBool(res))
	return 1
}

// Unit_PointValue -> Unit.PointValue() int
func bindUnitPointValue(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.PointValue()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Position -> Unit.Position() Vec2
func bindUnitPosition(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Position()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Unit_PropWindow -> Unit.PropWindow() float64
func bindUnitPropWindow(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.PropWindow()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Race -> Unit.Race() Race
func bindUnitRace(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Race()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_RallyPoint -> Unit.RallyPoint() Vec2
func bindUnitRallyPoint(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.RallyPoint()
	L.Push(vec2ToLua(L, res))
	return 1
}

// Unit_RallyUnit -> Unit.RallyUnit() Unit
func bindUnitRallyUnit(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.RallyUnit()
	L.Push(pushHandle(L, res))
	return 1
}

// Unit_Remove -> Unit.Remove()
func bindUnitRemove(L *lua.LState) int {
	recv := argUnit(L, 1)
	recv.Remove()
	return 0
}

// Unit_RemoveAbility -> Unit.RemoveAbility(ref AbilityRef) bool
func bindUnitRemoveAbility(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argAbilityRef(L, 2)
	res := recv.RemoveAbility(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_RemoveAllBuffs -> Unit.RemoveAllBuffs() int
func bindUnitRemoveAllBuffs(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.RemoveAllBuffs()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_RemoveBuff -> Unit.RemoveBuff(typ BuffType) bool
func bindUnitRemoveBuff(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argBuffType(L, 2)
	res := recv.RemoveBuff(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_SetAcquireRange -> Unit.SetAcquireRange(v float64)
func bindUnitSetAcquireRange(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetAcquireRange(a0)
	return 0
}

// Unit_SetAgility -> Unit.SetAgility(v int)
func bindUnitSetAgility(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetAgility(a0)
	return 0
}

// Unit_SetFacing -> Unit.SetFacing(a Angle)
func bindUnitSetFacing(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argAngle(L, 2)
	recv.SetFacing(a0)
	return 0
}

// Unit_SetFlyHeight -> Unit.SetFlyHeight(newHeight, ratePerSec float64)
func bindUnitSetFlyHeight(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	a1 := float64(L.CheckNumber(3))
	recv.SetFlyHeight(a0, a1)
	return 0
}

// Unit_SetHeroLevel -> Unit.SetHeroLevel(level int)
func bindUnitSetHeroLevel(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetHeroLevel(a0)
	return 0
}

// Unit_SetHeroXP -> Unit.SetHeroXP(xp int)
func bindUnitSetHeroXP(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetHeroXP(a0)
	return 0
}

// Unit_SetIntelligence -> Unit.SetIntelligence(v int)
func bindUnitSetIntelligence(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetIntelligence(a0)
	return 0
}

// Unit_SetInvulnerable -> Unit.SetInvulnerable(on bool)
func bindUnitSetInvulnerable(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckBool(2)
	recv.SetInvulnerable(a0)
	return 0
}

// Unit_SetLife -> Unit.SetLife(v float64)
func bindUnitSetLife(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetLife(a0)
	return 0
}

// Unit_SetMana -> Unit.SetMana(v float64)
func bindUnitSetMana(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetMana(a0)
	return 0
}

// Unit_SetMaxLife -> Unit.SetMaxLife(v float64)
func bindUnitSetMaxLife(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetMaxLife(a0)
	return 0
}

// Unit_SetMaxMana -> Unit.SetMaxMana(v float64)
func bindUnitSetMaxMana(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetMaxMana(a0)
	return 0
}

// Unit_SetMoveSpeed -> Unit.SetMoveSpeed(v float64)
func bindUnitSetMoveSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetMoveSpeed(a0)
	return 0
}

// Unit_SetName -> Unit.SetName(name string)
func bindUnitSetName(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckString(2)
	recv.SetName(a0)
	return 0
}

// Unit_SetOwner -> Unit.SetOwner(p Player, changeColor bool)
func bindUnitSetOwner(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argPlayer(L, 2)
	a1 := L.CheckBool(3)
	recv.SetOwner(a0, a1)
	return 0
}

// Unit_SetPaused -> Unit.SetPaused(paused bool)
func bindUnitSetPaused(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckBool(2)
	recv.SetPaused(a0)
	return 0
}

// Unit_SetPosition -> Unit.SetPosition(pos Vec2)
func bindUnitSetPosition(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argVec2(L, 2)
	recv.SetPosition(a0)
	return 0
}

// Unit_SetPropWindow -> Unit.SetPropWindow(radians float64)
func bindUnitSetPropWindow(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetPropWindow(a0)
	return 0
}

// Unit_SetStrength -> Unit.SetStrength(v int)
func bindUnitSetStrength(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetStrength(a0)
	return 0
}

// Unit_SetTurnSpeed -> Unit.SetTurnSpeed(radPerSec float64)
func bindUnitSetTurnSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := float64(L.CheckNumber(2))
	recv.SetTurnSpeed(a0)
	return 0
}

// Unit_SetUserData -> Unit.SetUserData(v int)
func bindUnitSetUserData(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckInt(2)
	recv.SetUserData(a0)
	return 0
}

// Unit_ShareVision -> Unit.ShareVision(p Player, share bool)
func bindUnitShareVision(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argPlayer(L, 2)
	a1 := L.CheckBool(3)
	recv.ShareVision(a0, a1)
	return 0
}

// Unit_Show -> Unit.Show(show bool)
func bindUnitShow(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckBool(2)
	recv.Show(a0)
	return 0
}

// Unit_SkillPoints -> Unit.SkillPoints() int
func bindUnitSkillPoints(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.SkillPoints()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Strength -> Unit.Strength() int
func bindUnitStrength(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Strength()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_SuspendExperience -> Unit.SuspendExperience(suspend bool)
func bindUnitSuspendExperience(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := L.CheckBool(2)
	recv.SuspendExperience(a0)
	return 0
}

// Unit_TurnSpeed -> Unit.TurnSpeed() float64
func bindUnitTurnSpeed(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.TurnSpeed()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_Type -> Unit.Type() UnitType
func bindUnitType(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.Type()
	L.Push(pushHandle(L, res))
	return 1
}

// Unit_UseItem -> Unit.UseItem(n int, opts ...UseOption) bool
func bindUnitUseItem(L *lua.LState) int {
	recv := argUnit(L, 1)
	if L.GetTop() > 2 {
		L.RaiseError("Unit_UseItem: options arguments are not yet bound from Lua (#267)")
		return 0
	}
	a0 := L.CheckInt(2)
	res := recv.UseItem(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Unit_UserData -> Unit.UserData() int
func bindUnitUserData(L *lua.LState) int {
	recv := argUnit(L, 1)
	res := recv.UserData()
	L.Push(lua.LNumber(res))
	return 1
}

// Unit_VisibleTo -> Unit.VisibleTo(p Player) bool
func bindUnitVisibleTo(L *lua.LState) int {
	recv := argUnit(L, 1)
	a0 := argPlayer(L, 2)
	res := recv.VisibleTo(a0)
	L.Push(lua.LBool(res))
	return 1
}

// Vec2_Add -> Vec2.Add(o Vec2) Vec2
func bindVec2Add(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argVec2(L, 2)
	res := recv.Add(a0)
	L.Push(vec2ToLua(L, res))
	return 1
}

// Vec2_AngleTo -> Vec2.AngleTo(o Vec2) Angle
func bindVec2AngleTo(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argVec2(L, 2)
	res := recv.AngleTo(a0)
	L.Push(angleToLua(res))
	return 1
}

// Vec2_DistanceTo -> Vec2.DistanceTo(o Vec2) float64
func bindVec2DistanceTo(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argVec2(L, 2)
	res := recv.DistanceTo(a0)
	L.Push(lua.LNumber(res))
	return 1
}

// Vec2_Polar -> Vec2.Polar(a Angle, dist float64) Vec2
func bindVec2Polar(L *lua.LState) int {
	recv := argVec2(L, 1)
	a0 := argAngle(L, 2)
	a1 := float64(L.CheckNumber(3))
	res := recv.Polar(a0, a1)
	L.Push(vec2ToLua(L, res))
	return 1
}
